# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

class MaterialyDialogDef(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(623, 377)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 330, 221, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabela = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(0)
        self.tabela.setRowCount(0)
        self.verticalLayout.addWidget(self.tabela)
        self.widget = QtGui.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.epoki_cb = QtGui.QComboBox(self.widget)
        self.epoki_cb.setObjectName("epoki_cb")
        self.horizontalLayout_3.addWidget(self.epoki_cb)
        self.kul_cb = QtGui.QComboBox(self.widget)
        self.kul_cb.setObjectName("kul_cb")
        self.horizontalLayout_3.addWidget(self.kul_cb)
        self.fun_cb = QtGui.QComboBox(self.widget)
        self.fun_cb.setObjectName("fun_cb")
        self.horizontalLayout_3.addWidget(self.fun_cb)
        self.ceram_sb = QtGui.QSpinBox(self.widget)
        self.ceram_sb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ceram_sb.setObjectName("ceram_sb")
        self.horizontalLayout_3.addWidget(self.ceram_sb)
        self.kam_sb = QtGui.QSpinBox(self.widget)
        self.kam_sb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.kam_sb.setObjectName("kam_sb")
        self.horizontalLayout_3.addWidget(self.kam_sb)
        self.met_sb = QtGui.QSpinBox(self.widget)
        self.met_sb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.met_sb.setObjectName("met_sb")
        self.horizontalLayout_3.addWidget(self.met_sb)
        self.dodaj_btn = QtGui.QToolButton(self.widget)
        self.dodaj_btn.setMaximumSize(QtCore.QSize(50, 25))
        self.dodaj_btn.setObjectName("dodaj_btn")
        self.horizontalLayout_3.addWidget(self.dodaj_btn)
        self.usun_btn = QtGui.QPushButton(self.widget)
        self.usun_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.usun_btn.setObjectName("usun_btn")
        self.horizontalLayout_3.addWidget(self.usun_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.dodaj_btn.setText(QtGui.QApplication.translate("Dialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.usun_btn.setText(QtGui.QApplication.translate("Dialog", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
