CREATE TABLE EKSPOZYCJA_DANE(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    EKSPONOWANY VARCHAR(1) CHECK (EKSPONOWANY IN ('T','N')),
    KRAW_STOKI VARCHAR(1) CHECK (KRAW_STOKI IN ('T','N')),
    SFALDOWANIA_CYPLE VARCHAR(1) CHECK (SFALDOWANIA_CYPLE IN ('T','N')),
    CYPLE_WYBITNE VARCHAR(1) CHECK (CYPLE_WYBITNE IN ('T','N')),
    WALY_GARBY VARCHAR(1) CHECK (WALY_GARBY IN ('T','N')),
    WYNIESIENIA_OKREZNE VARCHAR(1) CHECK (WYNIESIENIA_OKREZNE IN ('T','N')),
    OSLONIETY VARCHAR(1) CHECK (OSLONIETY IN ('T','N')),
    PODST_STOKU VARCHAR(1) CHECK (PODST_STOKU IN ('T','N')),
    DOLINY_NIECKI VARCHAR(1) CHECK (DOLINY_NIECKI IN ('T','N')),
    KOTLINKI_ZAGLEB VARCHAR(1) CHECK (KOTLINKI_ZAGLEB IN ('T','N')),
    JASKINIE VARCHAR(1) CHECK (JASKINIE IN ('T','N')),
    ROZMIAR DECIMAL(4,1),
    STOPIEN DECIMAL(3,1),
    KIERUNEK INTEGER CHECK (KIERUNEK BETWEEN 0 AND 256),
    UWAGI VARCHAR(255),
    CONSTRAINT EKSPOZYCJA_DANE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_EKSPOZYCJA_DANE_ST UNIQUE(ID, STANOWISKO)
    
);
CREATE TABLE FIZGEO_DANE(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    NADMORSKA VARCHAR(1) CHECK (NADMORSKA IN ('T','N')),
    W_MORZU VARCHAR(1) CHECK (W_MORZU IN ('T','N')),
    PLAZA VARCHAR(1) CHECK (PLAZA IN ('T','N')),
    MIERZEJA VARCHAR(1) CHECK (MIERZEJA IN ('T','N')),
    SKARPA VARCHAR(1) CHECK (SKARPA IN ('T','N')),
    WAL_WYDMOWY VARCHAR(1) CHECK (WAL_WYDMOWY IN ('T','N')),
    DUZE_DOLINY VARCHAR(1) CHECK (DUZE_DOLINY IN ('T','N')),
    W_WODZIE VARCHAR(1) CHECK (W_WODZIE IN ('T','N')),
    TER_DENNA VARCHAR(1) CHECK (TER_DENNA IN ('T','N')),
    TER_NADZALEWOWA VARCHAR(1) CHECK (TER_NADZALEWOWA IN ('T','N')),
    TER_WYZSZE VARCHAR(1) CHECK (TER_WYZSZE IN ('T','N')),
    BRZEG_WYSOCZYZNY VARCHAR(1) CHECK (BRZEG_WYSOCZYZNY IN ('T','N')),
    MALE_DOLINY VARCHAR(1) CHECK (MALE_DOLINY IN ('T','N')),
    DNO_DOLINY VARCHAR(1) CHECK (DNO_DOLINY IN ('T','N')),
    STOK_DOLINY VARCHAR(1) CHECK (STOK_DOLINY IN ('T','N')),
    KRAWEDZ_DOLINY VARCHAR(1) CHECK (KRAWEDZ_DOLINY IN ('T','N')),
    POZA_DOLINAMI VARCHAR(1) CHECK (POZA_DOLINAMI IN ('T','N')),
    ROWNINA VARCHAR(1) CHECK (ROWNINA IN ('T','N')),
    OBSZ_FALISTY VARCHAR(1) CHECK (OBSZ_FALISTY IN ('T','N')),
    OBSZ_PAGORKOWATY VARCHAR(1) CHECK (OBSZ_PAGORKOWATY IN ('T','N')),
    OBSZ_GORZYSTY VARCHAR(1) CHECK (OBSZ_GORZYSTY IN ('T','N')),
    UWAGI VARCHAR(255),
    CONSTRAINT FIZGEO_DANE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_FIZGEO_DANE_ST UNIQUE(ID, STANOWISKO)
);
CREATE TABLE OBSZAR_DANE(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    OBSERWACJA VARCHAR(1), -- UTRUDNIONA / BEZ PRZESZKOD
    POLE VARCHAR(1), -- OTWARTE / ZAMKNIETE
    NASYC_ROZKLAD VARCHAR(1), -- ROWNOMIERNY / NIEROWNOMIERNY
    NASYC_TYP VARCHAR(1), -- JEDNOCENTRYCZNE / WIELOCENTRYCZNE / DEKOCENTRYCZNE
    POWIERZCHNIA DECIMAL(9,2),
    GESTOSC_ZNAL VARCHAR(1), -- MALA / SREDNIA /DUZA
    UWAGI VARCHAR(255),
    CONSTRAINT OBSZAR_DANE_PKEY PRIMARY KEY (ID),
    CONSTRAINT CHECK_OBSERWACJA CHECK (OBSERWACJA IN ('U','B')),
    CONSTRAINT CHECK_POLE CHECK (POLE IN ('O','Z')),
    CONSTRAINT CHECK_NASYC_ROZKLAD CHECK (NASYC_ROZKLAD IN ('R','N')),
    CONSTRAINT CHECK_NASYC_TYP CHECK (NASYC_TYP IN ('J','W','D')),
    CONSTRAINT CHECK_GESTOSC_ZNAL CHECK (GESTOSC_ZNAL IN ('M','S','D')),
    CONSTRAINT UNIQUE_OBSZAR_DANE_ST UNIQUE(ID, STANOWISKO)
);
CREATE TABLE STANOWISKA(
    ID INTEGER NOT NULL,
    OBSZAR VARCHAR(8) NOT NULL,
    NR_OBSZAR VARCHAR(5) NOT NULL,
    MIEJSCOWOSC INTEGER NULL DEFAULT -1,
    NR_MIEJSCOWOSC VARCHAR(5) NULL DEFAULT '',
    GMINA INTEGER NULL DEFAULT -1,
    POWIAT INTEGER NULL DEFAULT -1,
    WOJEWODZTWO INTEGER NULL DEFAULT -1,
    RODZAJ_BADAN VARCHAR(1) NOT NULL DEFAULT '?',
    DATA VARCHAR(10),
    AUTOR VARCHAR(20),
    UWAGI VARCHAR(255),
    POWIERZCHNIA VARCHAR(2),
    ETYKIETA_X VARCHAR(20),
    ETYKIETA_Y VARCHAR(20),
    ETYKIETA_KOLOR VARCHAR(7),
    CONSTRAINT STANOWISKA_PKEY PRIMARY KEY(ID)
);
SELECT ADDGEOMETRYCOLUMN('STANOWISKA', 'WSPOLRZEDNE',
  2180, 'POLYGON', 'XY');

CREATE TABLE TEREN_DANE(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    ZABUDOWANY VARCHAR(1) CHECK (ZABUDOWANY IN ('T','N')),
    SRED_ZABUD VARCHAR(1) CHECK (SRED_ZABUD IN ('T','N')),
    LAS VARCHAR(1) CHECK (LAS IN ('T','N')),
    SAD VARCHAR(1) CHECK (SAD IN ('T','N')),
    PARK VARCHAR(1) CHECK (PARK IN ('T','N')),
    POLE_ORNE VARCHAR(1) CHECK (POLE_ORNE IN ('T','N')),
    LAKA VARCHAR(1) CHECK (LAKA IN ('T','N')),
    NIEUZYTEK VARCHAR(1) CHECK (NIEUZYTEK IN ('T','N')),
    TORF VARCHAR(1) CHECK (TORF IN ('T','N')),
    WODA VARCHAR(1) CHECK (WODA IN ('T','N')),
    BAGNO VARCHAR(1) CHECK (BAGNO IN ('T','N')), 
    PRYWATNY VARCHAR(1) CHECK (PRYWATNY IN ('T','N')),
    SPOLECZNY VARCHAR(1) CHECK (SPOLECZNY IN ('T','N')),
    PRZEMYSLOWY VARCHAR(1) CHECK (PRZEMYSLOWY IN ('T','N')),
    UWAGI VARCHAR(255), 
    CONSTRAINT TEREN_DANE_PKEY PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_TEREN_DANE_ST UNIQUE(ID, STANOWISKO)
);

CREATE TABLE WNIOSKI(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    WARTOSC VARCHAR(1), -- MALA / SREDNIA / DUZA
    INWENTARYZACJA VARCHAR(1) CHECK (INWENTARYZACJA IN ('T','N')),
    WYKOPALISKA VARCHAR(1) CHECK (WYKOPALISKA IN ('T','N')),
    INTERWENCJA VARCHAR(1) CHECK (INTERWENCJA IN ('T','N')),
    UWAGI VARCHAR(255),
    CONSTRAINT WNIOSKI_PKEY PRIMARY KEY (ID),
    CONSTRAINT CHECK_WARTOSC CHECK (WARTOSC IN ('M','S','D')),
    CONSTRAINT UNIQUE_WNIOSKI_ST UNIQUE(ID, STANOWISKO)
    
);

CREATE TABLE ZAGROZENIA(
    ID INTEGER NOT NULL,
    STANOWISKO INTEGER NOT NULL,
    WYSTEPOWANIE VARCHAR(1), -- ISTNIEJE / NIE ISTNIEJE
    CZAS VARCHAR(1), -- STALE / DORAZNE
    PRZYCZYNA_LUDZIE VARCHAR(1) CHECK (PRZYCZYNA_LUDZIE IN ('T','N')),
    PRZYCZYNA_NATURA VARCHAR(1) CHECK (PRZYCZYNA_NATURA IN ('T','N')),
    UZYTKOWNIK_SPOLECZNY VARCHAR(1) CHECK (UZYTKOWNIK_SPOLECZNY IN ('T','N')),
    UZYTKOWNIK_PRYWATNY VARCHAR(1) CHECK (UZYTKOWNIK_PRYWATNY IN ('T','N')),
    UWAGI VARCHAR(255),
    CONSTRAINT ZAGROZENIA_PKEY PRIMARY KEY (ID),
    CONSTRAINT CHECK_WYSTEPOWANIE CHECK (WYSTEPOWANIE IN ('I','N')),
    CONSTRAINT CHECK_CZAS CHECK (CZAS IN ('S','D')),
    CONSTRAINT UNIQUE_ZAGROZENIA_ST UNIQUE(ID, STANOWISKO)
);
CREATE TABLE AKTUALNOSCI(
  ID INTEGER NOT NULL,
  STANOWISKO INTEGER NOT NULL,
  MAGAZYN VARCHAR(20),
  NR_INWENTARZA VARCHAR(20),
  NR_KRZ VARCHAR(20), -- NR REJESTRU ZABYTKOW
  DATA_KRZ DATE, -- DATA WPISU DO REJESTRU
  PARK CHARACTER VARYING(20), -- PARK KULTUROWY
  PLAN CHARACTER VARYING(50),
  WLASCICIEL VARCHAR(500),
  UWAGI VARCHAR(255),
  CONSTRAINT AKTUALNOSCI_PKEY PRIMARY KEY (ID)
);
CREATE TABLE FAKTY
(
    ID INTEGER, 
    STANOWISKO INTEGER, 
    OKRESA VARCHAR(2),
    OKRESB VARCHAR(2),
    OKR_RELACJA VARCHAR(1) CHECK (OKR_RELACJA IN ('Z','P')),
    OKR_PEWNOSC DECIMAL(3,2),
    JEDA VARCHAR(6), 
    JEDB VARCHAR(6), 
    JED_RELACJA VARCHAR(1) CHECK (JED_RELACJA IN ('Z','P')), 
    JED_PEWNOSC DECIMAL(3,2), 
    FUNKCJA VARCHAR(8), 
    FUN_PEWNOSC DECIMAL(3,2), 
    MASOWY VARCHAR(50), 
    WYDZIELONY VARCHAR(50),
     CONSTRAINT FAKTY_PKEY PRIMARY KEY (ID),
     CONSTRAINT OKRESA_OKRESY_DZIEJOW_FKEY FOREIGN KEY(OKRESA) REFERENCES OKRESY_DZIEJOW(KOD),
     CONSTRAINT OKRESB_OKRESY_DZIEJOW_FKEY FOREIGN KEY(OKRESB) REFERENCES OKRESY_DZIEJOW(KOD),
     CONSTRAINT JEDA_JEDNOSTKI_FKEY FOREIGN KEY(JEDA) REFERENCES JEDNOSTKI(KOD),
     CONSTRAINT JEDB_JEDNOSTKI_FKEY FOREIGN KEY(JEDB) REFERENCES JEDNOSTKI(KOD),
     CONSTRAINT FUNKCJA_FUNKCJE_FKEY FOREIGN KEY(FUNKCJA) REFERENCES FUNKCJE(KOD)
);

CREATE TABLE FUNKCJE (
    KOD VARCHAR(8) PRIMARY KEY, 
    FUNKCJA VARCHAR(20), 
    CZLON1 VARCHAR(30), 
    CZLON2 VARCHAR(30), 
    CZLON3 VARCHAR(30), 
    NAZWA VARCHAR(90), 
    SKROT VARCHAR(20)
);

CREATE TABLE GLEBA_DANE -- GLEBY 
(
  ID INTEGER NOT NULL,
  STANOWISKO INTEGER NOT NULL,
  LUZNA CHARACTER VARYING(1) CHECK (LUZNA IN ('T','N')),
  ZWIEZLA CHARACTER VARYING(1) CHECK (ZWIEZLA IN ('T','N')),
  TORF_BAG CHARACTER VARYING(1) CHECK (TORF_BAG IN ('T','N')),
  KAMIENISTOSC CHARACTER VARYING(1) CHECK (KAMIENISTOSC IN ('M','S','D')),
  UWAGI CHARACTER VARYING(255),
  CONSTRAINT GLEBA_DANE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE GMINY (
    ID INTEGER PRIMARY KEY, 
    START VARCHAR(2) NOT NULL, 
    NAZWA VARCHAR(50)
);

CREATE TABLE JEDNOSTKI (
    KOD VARCHAR(6) PRIMARY KEY, 
    OKRES VARCHAR(1), 
    CZLON1 VARCHAR(30), 
    CZLON2 VARCHAR(30), 
    NAZWA VARCHAR(30), 
    SKROT VARCHAR(15), 
    START VARCHAR(2)
);

CREATE TABLE KARTY -- DO KAZDEGO STANOWISKA MOZNA DODAC INFORMACJE O WYPELNIONEJ KARCIE AZP
(
  ID INTEGER NOT NULL,
  STANOWISKO INTEGER NOT NULL,
  NAZWA_LOK VARCHAR(50),
  ARKUSZ_MAPY VARCHAR(10),
  DALSZE_LOSY VARCHAR(100),
  DZIEJE_BADAN VARCHAR(100),
  METRYKA_HIST VARCHAR(10),
  LITERATURA VARCHAR(100),
  DZIALKA_GEODEZYJNA VARCHAR(255),
  EGB CHARACTER VARYING(500) ,
  AUTORZY CHARACTER VARYING(255),
  CHRONOLOGIA CHARACTER VARYING(255), -- OKRESLIL CHRONOLOGIE
  KONSULTANT CHARACTER VARYING(255), -- SPRAWDZIL
  UWAGI VARCHAR(255),
  CONSTRAINT PK_KARTY PRIMARY KEY (ID)
);

CREATE TABLE MIEJSCA(
  ID INTEGER NOT NULL,
  NAZWA VARCHAR(50), 
  RODZAJ_BADAN VARCHAR(2) NOT NULL DEFAULT '?', -- L - LOT, P - POWIERZCHNIOWE, W - WERYFIKACJE,? - NIEOKRESLONE
  DATA VARCHAR(10) NOT NULL,
  AUTOR VARCHAR(100) NOT NULL,
  UWAGI VARCHAR(255),
  --WSPOLRZEDNE POINT,
  CONSTRAINT PK_MIEJSCA PRIMARY KEY (ID)
);

SELECT ADDGEOMETRYCOLUMN('MIEJSCA', 'WSPOLRZEDNE',
  2180, 'POLYGON', 'XY');

CREATE TABLE MIEJSCOWOSCI (
    ID INTEGER PRIMARY KEY, 
    START VARCHAR(2) NOT NULL, 
    NAZWA VARCHAR(50)
);

CREATE TABLE OKRESY_DZIEJOW ( 
    KOD VARCHAR(2) NOT NULL, 
    KOD_EPOKA VARCHAR(1) NOT NULL, 
    EPOKA VARCHAR(20) NOT NULL, 
    OKRES VARCHAR(30), 
    NAZWA VARCHAR(30) NOT NULL, 
    SKROT VARCHAR(20) NOT NULL, 
    CONSTRAINT OKRESY_DZIEJOW_PKEY PRIMARY KEY (KOD)
);

CREATE TABLE POWIATY(
    ID INTEGER PRIMARY KEY, 
    START VARCHAR(2) NOT NULL, 
    NAZWA VARCHAR(50)
);

CREATE TABLE TRASY(
  ID INTEGER NOT NULL,
  RODZAJ_BADAN VARCHAR(2) NOT NULL DEFAULT '?', -- L - LOT, P - POWIERZCHNIOWE, W - WERYFIKACJE, ? - NIEOKRESLONE
  DATA VARCHAR(10) NOT NULL,
  AUTOR VARCHAR(100) NOT NULL,
  ROZPOCZECIE VARCHAR(25),
  ZAKONCZENIE VARCHAR(25),
  CZESTOTLIWOSC INTEGER DEFAULT 0, -- CZESTOTLIWOSC ODCZYTOW W SEKUNDACH
  UWAGI VARCHAR(255),
  CONSTRAINT PK_TRASY PRIMARY KEY (ID)
);
SELECT ADDGEOMETRYCOLUMN('TRASY', 'WSPOLRZEDNE',
  2180, 'LINESTRING', 'XY');

CREATE TABLE WOJEWODZTWA (
    ID INTEGER PRIMARY KEY, 
    START VARCHAR(2) NOT NULL, 
    NAZWA VARCHAR(50)
);

CREATE TRIGGER DEL_STANOWISKO BEFORE DELETE ON STANOWISKA 
BEGIN
    DELETE FROM EKSPOZYCJA_DANE WHERE STANOWISKO = OLD.ID;
    DELETE FROM FIZGEO_DANE WHERE STANOWISKO = OLD.ID;
    DELETE FROM TEREN_DANE WHERE STANOWISKO = OLD.ID;
    DELETE FROM WNIOSKI WHERE STANOWISKO = OLD.ID;
    DELETE FROM ZAGROZENIA WHERE STANOWISKO = OLD.ID;
    DELETE FROM FAKTY WHERE STANOWISKO = OLD.ID;
    DELETE FROM KARTY WHERE STANOWISKO = OLD.ID;
    DELETE FROM OBSZAR_DANE WHERE STANOWISKO = OLD.ID;
    DELETE FROM AKTUALNOSCI WHERE STANOWISKO = OLD.ID;
    DELETE FROM MEDIA WHERE ID = (SELECT MEDIUM FROM ST_MEDIA WHERE STANOWISKO = OLD.ID);
    DELETE FROM ST_MEDIA WHERE STANOWISKO = OLD.ID;
    DELETE FROM GLEBA WHERE STANOWISKO = OLD.ID;
END;

CREATE TABLE ST_MEDIA(
    MEDIUM INTEGER, 
    STANOWISKO INTEGER, 
    TYP VARCHAR(1)
);

CREATE TABLE MEDIA(
    ID INTEGER NOT NULL PRIMARY KEY, 
    SYGNATURA VARCHAR(50), 
    PLIK VARCHAR(20), 
    FORMAT VARCHAR(4), 
    TABELA VARCHAR(1), 
    DANE BLOB
);

CREATE TABLE USTAWIENIA(
    KLUCZ VARCHAR(10) PRIMARY KEY, 
    WARTOSC VARCHAR(20)
);

CREATE TABLE PROJEKTY(
    ID INTEGER PRIMARY KEY,
    START VARCHAR(2), 
    NAZWA VARCHAR(255)
);

CREATE TABLE PODMIOTY(
    ID INTEGER PRIMARY KEY,
    START VARCHAR(2),
    NAZWA VARCHAR(255)
);

CREATE TABLE ZDJECIA_LOTNICZE(
  ID INTEGER NOT NULL,
  FOLDER VARCHAR(20),
  KLATKA VARCHAR(20),
  MIEJSCOWOSC INTEGER,
  GMINA INTEGER,
  POWIAT INTEGER,
  WOJEWODZTWO INTEGER,
  AUTOR INTEGER,
  PILOT INTEGER,
  DATA_WYKONANIA VARCHAR(10),
  CZAS_WYKONANIA VARCHAR(20),
  PRAWA_AUTORSKIE VARCHAR(255),
  PROJEKT INTEGER,
  NUMER VARCHAR(100),
  ZLECENIODAWCA INTEGER,
  PLATNIK INTEGER,
  NOSNIK VARCHAR(1),
  CONSTRAINT PK_ZDJECIA_LOTNICZE PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_ZDJECIA_LOTNICZE UNIQUE (FOLDER, KLATKA)
);

SELECT ADDGEOMETRYCOLUMN('ZDJECIA_LOTNICZE', 'WSPOLRZEDNE',
  2180, 'POINT', 'XY');

INSERT INTO USTAWIENIA VALUES('WERSJA','0002');
