PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE EKSPOZYCJA_DANE(
    id integer not null,
    stanowisko integer not null,
    eksponowany varchar(1),
    kraw_stoki varchar(1),
    sfaldowania_cyple varchar(1),
    cyple_wybitne varchar(1),
    waly_garby varchar(1),
    wyniesienia_okrezne varchar(1),
    osloniety varchar(1),
    podst_stoku varchar(1),
    doliny_niecki varchar(1),
    kotlinki_zagleb varchar(1),
    jaskinie varchar(1),
    rozmiar decimal(4,1),
    stopien decimal(3.1),
    kierunek integer,
    uwagi varchar(255),
    CONSTRAINT pk_ekspozycja PRIMARY KEY (id)
    
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE FIZGEO_DANE(
    id integer not null,
    stanowisko integer not null,
    nadmorska varchar(1),
    w_morzu varchar(1),
    plaza varchar(1),
    mierzeja varchar(1),
    skarpa varchar(1),
    wal_wydmowy varchar(1),
    duze_doliny varchar(1),
    w_wodzie varchar(1),
    ter_denna varchar(1),
    ter_nadzalewowa varchar(1),
    ter_wyzsze varchar(1),
    brzeg_wysoczyzny varchar(1),
    male_doliny varchar(1),
    dno_doliny varchar(1),
    stok_doliny varchar(1),
    krawedz_doliny varchar(1),
    poza_dolinami varchar(1),
    rownina varchar(1),
    obsz_falisty varchar(1),
    obsz_pagorkowaty varchar(1),
    obsz_gorzysty varchar(1),
    CONSTRAINT pk_fizgeo PRIMARY KEY (id)
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE OBSZAR_DANE(
    id integer not null,
    stanowisko integer not null,
    obserwacja varchar(1), -- utrudniona / bez przeszkod
    pole varchar(1), -- otwarte / zamkniete
    nasyc_rozklad varchar(1), -- rownomierny / nierownomierny
    nasyc_typ varchar(1), -- jednocentryczne / wielocentryczne / dekocentryczne
    powierzchnia decimal(9,2),
    gestosc_znal varchar(1), -- mala / srednia /duza
    CONSTRAINT pk_obszar PRIMARY KEY (id),
    CONSTRAINT check_obserwacja CHECK (obserwacja in ('U','B')),
    CONSTRAINT check_pole CHECK (pole in ('O','Z')),
    CONSTRAINT check_nrozklad CHECK (nasyc_rozklad in ('R','N')),
    CONSTRAINT check_ntyp CHECK (nasyc_typ in ('J','W','D')),
    CONSTRAINT check_gestoscz CHECK (gestosc_znal in ('M','S','D'))
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE STANOWISKA(
    id integer not null,
    obszar varchar(8) not null,
    nr_obszar varchar(5) not null,
    miejscowosc integer null default -1,
    nr_miejscowosc varchar(5) null default '',
    gmina integer null default -1,
    powiat integer null default -1,
    wojewodztwo integer null default -1,
    rodzaj_badan varchar(1) not null default '?',
    data varchar(10),
    autor varchar(20),
    uwagi varchar(255),
    wspolrzedne POLYGON,
    constraint pk_stanowiska primary key(id)
);
CREATE TRIGGER "ggu_stanowiska_wspolrzedne" BEFORE UPDATE ON stanowiska
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'stanowiska.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'stanowiska' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
CREATE TRIGGER "ggi_stanowiska_wspolrzedne" BEFORE INSERT ON stanowiska
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'stanowiska.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'stanowiska' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE TEREN_DANE(
    id integer not null,
    stanowisko integer not null,
    zabudowany varchar(1),
    sred_zabud varchar(1),
    las varchar(1),
    sad varchar(1),
    park varchar(1),
    pole_orne varchar(1),
    laka varchar(1),
    rolniczy varchar(1),
    spoleczny varchar(1),
    przemyslowy varchar(1),
    uwagi varchar(255),
    CONSTRAINT pk_teren PRIMARY KEY (id)
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE WNIOSKI(
    id integer not null,
    stanowisko integer not null,
    wartosc varchar(1), -- mala / srednia / duza
    inwentaryzacja varchar(1),
    wykopaliska varchar(1),
    interwencja varchar(1),
    uwagi varchar(255),
    CONSTRAINT pk_wnioski PRIMARY KEY (id),
    CONSTRAINT check_wartosc CHECK (wartosc in ('M','S','D'))
    
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE ZAGROZENIA(
    id integer not null,
    stanowisko integer not null,
    wystepowanie varchar(1) not null, -- istnieje / nie istnieje
    przyczyna varchar(1), -- ludzie / natura
    uzytkownik varchar(1), -- wypelniane jezeli przyczyna == ludzie: uzytkownik spoleczny / prywatny
    uwagi varchar(255),
    CONSTRAINT pk_zagrozenia PRIMARY KEY (id),
    CONSTRAINT check_wystepowanie CHECK (wystepowanie in ('I','N')),
    CONSTRAINT check_przyczyna CHECK (przyczyna in ('L','N')),
    CONSTRAINT check_uzytkownik CHECK (uzytkownik in ('S','P'))
);
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE powiaty(id integer primary key, start varchar(2) not null, nazwa varchar(50));
INSERT INTO "powiaty" VALUES(1,'PO','POZNAŃ');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE wojewodztwa(id integer primary key, start varchar(2) not null, nazwa varchar(50));
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE miejsca(
  id integer NOT NULL,
  nazwa varchar(50), 
  rodzaj_badan varchar(2) not null default '?', -- L - lot, P - powierzchniowe, W - weryfikacje,? - nieokreslone
  data varchar(10) not null,
  autor varchar(100) not null,
  uwagi varchar(255),
  wspolrzedne POINT,
  CONSTRAINT pk_miejsca PRIMARY KEY (id)
);
CREATE TRIGGER "ggi_miejsca_wspolrzedne" BEFORE INSERT ON miejsca
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'miejsca.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'miejsca' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
CREATE TRIGGER "ggu_miejsca_wspolrzedne" BEFORE UPDATE ON miejsca
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'miejsca.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'miejsca' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE miejscowosci(id integer primary key, start varchar(2) not null, nazwa varchar(50));
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE funkcje(kod varchar(8) primary key, funkcja varchar(20), czlon1 varchar(30), czlon2 varchar(30), czlon3 varchar(30), nazwa varchar(90), skrot varchar(20));
INSERT INTO "funkcje" VALUES('OT01','O','FORTALICJA',NULL,NULL,'FORTALICJA','FORTALICJA');
INSERT INTO "funkcje" VALUES('OF','O','FORTYFIKACJE',NULL,NULL,'FORTYFIKACJE','FORYFIK.');
INSERT INTO "funkcje" VALUES('OF01','O','FORTYFIKACJE','STAŁE',NULL,'FORTYFIKACJE STAŁE','FORYFIK.');
INSERT INTO "funkcje" VALUES('OF02','O','FORTYFIKACJE','POLOWE',NULL,'FORTYFIKACJE POLOWE','FORYFIK.');
INSERT INTO "funkcje" VALUES('OG','O','GRODZISKO',NULL,NULL,'GRODZISKO','GRODZ.');
INSERT INTO "funkcje" VALUES('OG01','O','GRODZISKO','CYPLOWE',NULL,'GRODZISKO CYPLOWE','GRODZ.');
INSERT INTO "funkcje" VALUES('OG02','O','GRODZISKO','STOŻKOWATE',NULL,'GRODZISKO STOŻKOWATE','GRODZ.');
INSERT INTO "funkcje" VALUES('OG03','O','GRODZISKO','PIERŚCIENIOWATE',NULL,'GRODZISKO PIERŚCIENIOWATE','GRODZ.');
INSERT INTO "funkcje" VALUES('BD','B','DEPOZYT',NULL,NULL,'DEPOZYT','DEPOZYT');
INSERT INTO "funkcje" VALUES('BG','B','GŁAZ NARZUTOWY',NULL,NULL,'GŁAZ NARZUTOWY','GŁAZ');
INSERT INTO "funkcje" VALUES('BS','B','KOŚCIÓŁ, ŚWIĄTYNIA, KAPLICA',NULL,NULL,'KOŚCIÓŁ, ŚWIĄTYNIA, KAPLICA','KOŚCIÓŁ');
INSERT INTO "funkcje" VALUES('BK','B','KRĄG KAMIENNY',NULL,NULL,'KRĄG KAMIENNY','KRĄG KAM.');
INSERT INTO "funkcje" VALUES('BM','B','MENHIR',NULL,NULL,'MENHIR','MENHIR');
INSERT INTO "funkcje" VALUES('BL','B','MIEJSCE KULTU',NULL,NULL,'MIEJSCE KULTU','MIEJ. KULT.');
INSERT INTO "funkcje" VALUES('BO01','B','MIEJSCE OFIARNE','LĄDOWE',NULL,'MIEJSCE OFIARNE LĄDOWE','MIEJ. OFI.');
INSERT INTO "funkcje" VALUES('BO02','B','MIEJSCE OFIARNE','BAGIENNE/WODNE',NULL,'MIEJSCE OFIARNE BAGIENNE/WODNE','MIEJ. OFI.');
INSERT INTO "funkcje" VALUES('BZ','B','POCHÓWEK ZWIERZĘCY',NULL,NULL,'POCHÓWEK ZWIERZĘCY','POCH. ZWI');
INSERT INTO "funkcje" VALUES('BR','B','ZAŁOŻENIE Z ROWAMI',NULL,NULL,'ZAŁOŻENIE Z ROWAMI','ZAŁ. Z ROW.');
INSERT INTO "funkcje" VALUES('BE','B','ZESPÓŁ KLASZTORNY/EREMICKI',NULL,NULL,'ZESPÓŁ KLASZTORNY/EREMICKI','ZESP KLASZ.');
INSERT INTO "funkcje" VALUES('MD','M','DWÓR',NULL,NULL,'DWÓR','DWÓR');
INSERT INTO "funkcje" VALUES('MF','M','FOLWARK',NULL,NULL,'FOLWARK','FOLWARK');
INSERT INTO "funkcje" VALUES('MJ','M','JASKINIA',NULL,NULL,'JASKINIA','JASKI.');
INSERT INTO "funkcje" VALUES('MU','M','JURYDYKA',NULL,NULL,'JURYDYKA','JURYDYK.');
INSERT INTO "funkcje" VALUES('MM','M','MIASTO',NULL,NULL,'MIASTO','MIASTO');
INSERT INTO "funkcje" VALUES('MO','M','OBOZOWISKO',NULL,NULL,'OBOZOWISKO','OBOZ.');
INSERT INTO "funkcje" VALUES('MO01','M','OBOZOWISKO','PODSTAWOWE',NULL,'OBOZOWISKO PODSTAWOWE','OBOZ.');
INSERT INTO "funkcje" VALUES('MO02','M','OBOZOWISKO','PUNKT ETAPOWY',NULL,'OBOZOWISKO PUNKT ETAPOWY','OBOZ.');
INSERT INTO "funkcje" VALUES('MO03','M','OBOZOWISKO','SPECJALNE/ FUNKCJONALNE',NULL,'OBOZOWISKO SPECJALNE/ FUNKCJONALNE','OBOZ.');
INSERT INTO "funkcje" VALUES('MS','M','OSADA',NULL,NULL,'OSADA','OSADA');
INSERT INTO "funkcje" VALUES('MS01','M','OSADA','NAWODNA/PALAFIT',NULL,'OSADA NAWODNA/PALAFIT','OSADA');
INSERT INTO "funkcje" VALUES('MS02','M','OSADA','O',NULL,'OSADA O','OSADA');
INSERT INTO "funkcje" VALUES('MS03','M','OSADA','PRZYGRODOWA',NULL,'OSADA PRZYGRODOWA','OSADA');
INSERT INTO "funkcje" VALUES('MS04','M','OSADA','OTOCZONA ROWEM/ROWAMI',NULL,'OSADA OTOCZONA ROWEM/ROWAMI','OSADA');
INSERT INTO "funkcje" VALUES('MS05','M','OSADA','OTWARTA',NULL,'OSADA OTWARTA','OSADA');
INSERT INTO "funkcje" VALUES('MS06','M','OSADA','WIEŚ',NULL,'OSADA WIEŚ','OSADA');
INSERT INTO "funkcje" VALUES('MS07','M','OSADA','INNA',NULL,'OSADA INNA','OSADA');
INSERT INTO "funkcje" VALUES('MP','M','PAŁAC',NULL,NULL,'PAŁAC','PAŁAC');
INSERT INTO "funkcje" VALUES('MR','M','PARK',NULL,NULL,'PARK','PARK');
INSERT INTO "funkcje" VALUES('MN','M','PUNKT OSADNICZY',NULL,NULL,'PUNKT OSADNICZY','PKT. OSAD');
INSERT INTO "funkcje" VALUES('MA','M','RELIKTY ARCHITEKTURY',NULL,NULL,'RELIKTY ARCHITEKTURY','REL. ARCH.');
INSERT INTO "funkcje" VALUES('MC','M','SCHRONISKO SKALNE',NULL,NULL,'SCHRONISKO SKALNE','SCHR. SKAL');
INSERT INTO "funkcje" VALUES('ML','M','ŚLAD OSADNICZY',NULL,NULL,'ŚLAD OSADNICZY','ŚL. OSAD');
INSERT INTO "funkcje" VALUES('MZ','M','ZAMEK',NULL,NULL,'ZAMEK','ZAMEK');
INSERT INTO "funkcje" VALUES('S','S',NULL,NULL,NULL,NULL,'SEPULK.');
INSERT INTO "funkcje" VALUES('SB','S','GRÓB BIRYTUALNY',NULL,NULL,'GRÓB BIRYTUALNY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB01B','S','GRÓB BIRYTUALNY','KURHAN','BEZ NASYPU','GRÓB BIRYTUALNY KURHAN  BEZ NASYPU','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB01K','S','GRÓB BIRYTUALNY','KURHAN','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB BIRYTUALNY KURHAN  Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB01P','S','GRÓB BIRYTUALNY','KURHAN','Z PŁASZCZEM KAMIENNYM','GRÓB BIRYTUALNY KURHAN  Z PŁASZCZEM KAMIENNYM','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB01N','S','GRÓB BIRYTUALNY','KURHAN','Z ZACHOWANYM NASYPEM','GRÓB BIRYTUALNY KURHAN  Z ZACHOWANYM NASYPEM','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB02','S','GRÓB BIRYTUALNY','MEGAKSYLON',NULL,'GRÓB BIRYTUALNY MEGAKSYLON','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03D','S','GRÓB BIRYTUALNY','MEGALIT','DOLMEN','GRÓB BIRYTUALNY MEGALIT DOLMEN','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03G','S','GRÓB BIRYTUALNY','MEGALIT','GALERIOWY','GRÓB BIRYTUALNY MEGALIT GALERIOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03O','S','GRÓB BIRYTUALNY','MEGALIT','KORYTARZOWY','GRÓB BIRYTUALNY MEGALIT KORYTARZOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03Q','S','GRÓB BIRYTUALNY','MEGALIT','QUASI-MEGALIT','GRÓB BIRYTUALNY MEGALIT QUASI-MEGALIT','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03S','S','GRÓB BIRYTUALNY','MEGALIT','SKRZYNKOWY','GRÓB BIRYTUALNY MEGALIT SKRZYNKOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB03U','S','GRÓB BIRYTUALNY','MEGALIT','TYPU KUJAWSKIEGO','GRÓB BIRYTUALNY MEGALIT TYPU KUJAWSKIEGO','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB04','S','GRÓB BIRYTUALNY','NISZOWY/ KATAKUMBOWY',NULL,'GRÓB BIRYTUALNY NISZOWY/ KATAKUMBOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB05S','S','GRÓB BIRYTUALNY','PŁASKI','SKRZYNKOWY','GRÓB BIRYTUALNY PŁASKI SKRZYNKOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB05K','S','GRÓB BIRYTUALNY','PŁASKI','W OBSTAWIE KAMIENNEJ','GRÓB BIRYTUALNY PŁASKI W OBSTAWIE KAMIENNEJ','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB05W','S','GRÓB BIRYTUALNY','PŁASKI','WARSTWOWY','GRÓB BIRYTUALNY PŁASKI WARSTWOWY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB05I','S','GRÓB BIRYTUALNY','PŁASKI','INNY','GRÓB BIRYTUALNY PŁASKI INNY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SB06','S','GRÓB BIRYTUALNY','INNY',NULL,'GRÓB BIRYTUALNY INNY','GRÓB BIR.');
INSERT INTO "funkcje" VALUES('SR','S','CMENTARZYSKO BIRYTUALNE',NULL,NULL,'CMENTARZYSKO BIRYTUALNE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR01B','S','CMENTARZYSKO BIRYTUALNE','KURHANOWE','BEZ NASYPÓW','CMENTARZYSKO BIRYTUALNE KURHANOWE BEZ NASYPÓW','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR01K','S','CMENTARZYSKO BIRYTUALNE','KURHANOWE','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CMENTARZYSKO BIRYTUALNE KURHANOWE Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR01P','S','CMENTARZYSKO BIRYTUALNE','KURHANOWE','Z PŁASZCZEM KAMIENNYM','CMENTARZYSKO BIRYTUALNE KURHANOWE Z PŁASZCZEM KAMIENNYM','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR01N','S','CMENTARZYSKO BIRYTUALNE','KURHANOWE','Z ZACHOWANYMI NASYPAMI','CMENTARZYSKO BIRYTUALNE KURHANOWE Z ZACHOWANYMI NASYPAMI','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02D','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','DOLMENY','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE DOLMENY','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02G','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','MEGALITY GALERIOWE','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE MEGALITY GALERIOWE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02O','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','MEGALITY KORYTARZOWE','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE MEGALITY KORYTARZOWE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02S','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','MEGALITY SKRZYNKOWE','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE MEGALITY SKRZYNKOWE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02U','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','MEGALITY TYPU KUJAWSKIEGO','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE MEGALITY TYPU KUJAWSKIEGO','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR02Q','S','CMENTARZYSKO BIRYTUALNE','MEGALITYCZNE','QUASI-MEGALITY','CMENTARZYSKO BIRYTUALNE MEGALITYCZNE QUASI-MEGALITY','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR03S','S','CMENTARZYSKO BIRYTUALNE','PŁASKIE','GROBY SKRZYNKOWE','CMENTARZYSKO BIRYTUALNE PŁASKIE GROBY SKRZYNKOWE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR03K','S','CMENTARZYSKO BIRYTUALNE','PŁASKIE','GROBY W OBSTAWIE KAMIENNEJ','CMENTARZYSKO BIRYTUALNE PŁASKIE GROBY W OBSTAWIE KAMIENNEJ','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR03W','S','CMENTARZYSKO BIRYTUALNE','PŁASKIE','GROBY WARSTWOWE','CMENTARZYSKO BIRYTUALNE PŁASKIE GROBY WARSTWOWE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR03I','S','CMENTARZYSKO BIRYTUALNE','PŁASKIE','INNE','CMENTARZYSKO BIRYTUALNE PŁASKIE INNE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SR04','S','CMENTARZYSKO BIRYTUALNE','INNE',NULL,'CMENTARZYSKO BIRYTUALNE INNE','CM. BIR.');
INSERT INTO "funkcje" VALUES('SS','S','GRÓB SZKIELETOWY',NULL,NULL,'GRÓB SZKIELETOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS01B','S','GRÓB SZKIELETOWY','KURHAN','BEZ NASYPU','GRÓB SZKIELETOWY KURHAN  BEZ NASYPU','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS01K','S','GRÓB SZKIELETOWY','KURHAN','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB SZKIELETOWY KURHAN  Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS01P','S','GRÓB SZKIELETOWY','KURHAN','Z PŁASZCZEM KAMIENNYM','GRÓB SZKIELETOWY KURHAN  Z PŁASZCZEM KAMIENNYM','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS01N','S','GRÓB SZKIELETOWY','KURHAN','Z ZACHOWANYM NASYPEM','GRÓB SZKIELETOWY KURHAN  Z ZACHOWANYM NASYPEM','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS02','S','GRÓB SZKIELETOWY','MEGAKSYLON',NULL,'GRÓB SZKIELETOWY MEGAKSYLON','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03D','S','GRÓB SZKIELETOWY','MEGALIT','DOLMEN','GRÓB SZKIELETOWY MEGALIT DOLMEN','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03G','S','GRÓB SZKIELETOWY','MEGALIT','GALERIOWY','GRÓB SZKIELETOWY MEGALIT GALERIOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03O','S','GRÓB SZKIELETOWY','MEGALIT','KORYTARZOWY','GRÓB SZKIELETOWY MEGALIT KORYTARZOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03Q','S','GRÓB SZKIELETOWY','MEGALIT','QUASI-MEGALIT','GRÓB SZKIELETOWY MEGALIT QUASI-MEGALIT','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03S','S','GRÓB SZKIELETOWY','MEGALIT','SKRZYNKOWY','GRÓB SZKIELETOWY MEGALIT SKRZYNKOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS03U','S','GRÓB SZKIELETOWY','MEGALIT','TYPU KUJAWSKIEGO','GRÓB SZKIELETOWY MEGALIT TYPU KUJAWSKIEGO','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS04','S','GRÓB SZKIELETOWY','NISZOWY/ KATAKUMBOWY',NULL,'GRÓB SZKIELETOWY NISZOWY/ KATAKUMBOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS05S','S','GRÓB SZKIELETOWY','PŁASKI','SKRZYNKOWY','GRÓB SZKIELETOWY PŁASKI SKRZYNKOWY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS05K','S','GRÓB SZKIELETOWY','PŁASKI','W OBSTAWIE KAMIENNEJ','GRÓB SZKIELETOWY PŁASKI W OBSTAWIE KAMIENNEJ','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS05I','S','GRÓB SZKIELETOWY','PŁASKI','INNY','GRÓB SZKIELETOWY PŁASKI INNY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SS06','S','GRÓB SZKIELETOWY','INNY',NULL,'GRÓB SZKIELETOWY INNY','GRÓB. SZK.');
INSERT INTO "funkcje" VALUES('SZ','S','CMENTARZYSKO SZKIELETOWE',NULL,NULL,'CMENTARZYSKO SZKIELETOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ01B','S','CMENTARZYSKO SZKIELETOWE','KURHANOWE','BEZ NASYPÓW','CMENTARZYSKO SZKIELETOWE KURHANOWE BEZ NASYPÓW','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ01K','S','CMENTARZYSKO SZKIELETOWE','KURHANOWE','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CMENTARZYSKO SZKIELETOWE KURHANOWE Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ01P','S','CMENTARZYSKO SZKIELETOWE','KURHANOWE','Z PŁASZCZEM KAMIENNYM','CMENTARZYSKO SZKIELETOWE KURHANOWE Z PŁASZCZEM KAMIENNYM','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ01N','S','CMENTARZYSKO SZKIELETOWE','KURHANOWE','Z ZACHOWANYMI NASYPAMI','CMENTARZYSKO SZKIELETOWE KURHANOWE Z ZACHOWANYMI NASYPAMI','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02D','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','DOLMENY','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE DOLMENY','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02G','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','MEGALITY GALERIOWE','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE MEGALITY GALERIOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02O','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','MEGALITY KORYTARZOWE','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE MEGALITY KORYTARZOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02S','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','MEGALITY SKRZYNKOWE','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE MEGALITY SKRZYNKOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02U','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','MEGALITY TYPU KUJAWSKIEGO','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE MEGALITY TYPU KUJAWSKIEGO','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ02Q','S','CMENTARZYSKO SZKIELETOWE','MEGALITYCZNE','QUASI-MEGALITY','CMENTARZYSKO SZKIELETOWE MEGALITYCZNE QUASI-MEGALITY','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ03S','S','CMENTARZYSKO SZKIELETOWE','PŁASKIE','GROBY SKRZYNKOWE','CMENTARZYSKO SZKIELETOWE PŁASKIE GROBY SKRZYNKOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ03K','S','CMENTARZYSKO SZKIELETOWE','PŁASKIE','GROBY W OBSTAWIE KAMIENNEJ','CMENTARZYSKO SZKIELETOWE PŁASKIE GROBY W OBSTAWIE KAMIENNEJ','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ03W','S','CMENTARZYSKO SZKIELETOWE','PŁASKIE','GROBY WARSTWOWE','CMENTARZYSKO SZKIELETOWE PŁASKIE GROBY WARSTWOWE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ03I','S','CMENTARZYSKO SZKIELETOWE','PŁASKIE','INNE','CMENTARZYSKO SZKIELETOWE PŁASKIE INNE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SZ04','S','CMENTARZYSKO SZKIELETOWE','INNE',NULL,'CMENTARZYSKO SZKIELETOWE INNE','CM. SZK.');
INSERT INTO "funkcje" VALUES('SP','S','GRÓB CIAŁOPALNY',NULL,NULL,'GRÓB CIAŁOPALNY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP01B','S','GRÓB CIAŁOPALNY','KURHAN','BEZ NASYPU','GRÓB CIAŁOPALNY KURHAN  BEZ NASYPU','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP01K','S','GRÓB CIAŁOPALNY','KURHAN','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB CIAŁOPALNY KURHAN  Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP01P','S','GRÓB CIAŁOPALNY','KURHAN','Z PŁASZCZEM KAMIENNYM','GRÓB CIAŁOPALNY KURHAN  Z PŁASZCZEM KAMIENNYM','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP01N','S','GRÓB CIAŁOPALNY','KURHAN','Z ZACHOWANYM NASYPEM','GRÓB CIAŁOPALNY KURHAN  Z ZACHOWANYM NASYPEM','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP02','S','GRÓB CIAŁOPALNY','MEGAKSYLON',NULL,'GRÓB CIAŁOPALNY MEGAKSYLON','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03D','S','GRÓB CIAŁOPALNY','MEGALIT','DOLMEN','GRÓB CIAŁOPALNY MEGALIT DOLMEN','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03G','S','GRÓB CIAŁOPALNY','MEGALIT','GALERIOWY','GRÓB CIAŁOPALNY MEGALIT GALERIOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03O','S','GRÓB CIAŁOPALNY','MEGALIT','KORYTARZOWY','GRÓB CIAŁOPALNY MEGALIT KORYTARZOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03Q','S','GRÓB CIAŁOPALNY','MEGALIT','QUASI-MEGALIT','GRÓB CIAŁOPALNY MEGALIT QUASI-MEGALIT','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03S','S','GRÓB CIAŁOPALNY','MEGALIT','SKRZYNKOWY','GRÓB CIAŁOPALNY MEGALIT SKRZYNKOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP03U','S','GRÓB CIAŁOPALNY','MEGALIT','TYPU KUJAWSKIEGO','GRÓB CIAŁOPALNY MEGALIT TYPU KUJAWSKIEGO','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP04','S','GRÓB CIAŁOPALNY','NISZOWY/ KATAKUMBOWY',NULL,'GRÓB CIAŁOPALNY NISZOWY/ KATAKUMBOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05J','S','GRÓB CIAŁOPALNY','PŁASKI','JAMOWY','GRÓB CIAŁOPALNY PŁASKI JAMOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05P','S','GRÓB CIAŁOPALNY','PŁASKI','POPIELNICOWY','GRÓB CIAŁOPALNY PŁASKI POPIELNICOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05S','S','GRÓB CIAŁOPALNY','PŁASKI','SKRZYNKOWY','GRÓB CIAŁOPALNY PŁASKI SKRZYNKOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05K','S','GRÓB CIAŁOPALNY','PŁASKI','W OBSTAWIE KAMIENNEJ','GRÓB CIAŁOPALNY PŁASKI W OBSTAWIE KAMIENNEJ','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05W','S','GRÓB CIAŁOPALNY','PŁASKI','WARSTWOWY','GRÓB CIAŁOPALNY PŁASKI WARSTWOWY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP05I','S','GRÓB CIAŁOPALNY','PŁASKI','INNY','GRÓB CIAŁOPALNY PŁASKI INNY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SP06','S','GRÓB CIAŁOPALNY','INNY',NULL,'GRÓB CIAŁOPALNY INNY','GRÓB CIA.');
INSERT INTO "funkcje" VALUES('SL','S','CMENTARZYSKO CIAŁOPALNE',NULL,NULL,'CMENTARZYSKO CIAŁOPALNE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL01B','S','CMENTARZYSKO CIAŁOPALNE','KURHANOWE','BEZ NASYPÓW','CMENTARZYSKO CIAŁOPALNE KURHANOWE BEZ NASYPÓW','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL01K','S','CMENTARZYSKO CIAŁOPALNE','KURHANOWE','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CMENTARZYSKO CIAŁOPALNE KURHANOWE Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL01P','S','CMENTARZYSKO CIAŁOPALNE','KURHANOWE','Z PŁASZCZEM KAMIENNYM','CMENTARZYSKO CIAŁOPALNE KURHANOWE Z PŁASZCZEM KAMIENNYM','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL01N','S','CMENTARZYSKO CIAŁOPALNE','KURHANOWE','Z ZACHOWANYMI NASYPAMI','CMENTARZYSKO CIAŁOPALNE KURHANOWE Z ZACHOWANYMI NASYPAMI','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02D','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','DOLMENY','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE DOLMENY','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02G','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','MEGALITY GALERIOWE','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE MEGALITY GALERIOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02O','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','MEGALITY KORYTARZOWE','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE MEGALITY KORYTARZOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02S','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','MEGALITY SKRZYNKOWE','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE MEGALITY SKRZYNKOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02U','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','MEGALITY TYPU KUJAWSKIEGO','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE MEGALITY TYPU KUJAWSKIEGO','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL02Q','S','CMENTARZYSKO CIAŁOPALNE','MEGALITYCZNE','QUASI-MEGALITY','CMENTARZYSKO CIAŁOPALNE MEGALITYCZNE QUASI-MEGALITY','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03J','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','GROBY JAMOWE','CMENTARZYSKO CIAŁOPALNE PŁASKIE GROBY JAMOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03P','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','GROBY POPIELNICOWE','CMENTARZYSKO CIAŁOPALNE PŁASKIE GROBY POPIELNICOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03S','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','GROBY SKRZYNKOWE','CMENTARZYSKO CIAŁOPALNE PŁASKIE GROBY SKRZYNKOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03K','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','GROBY W OBSTAWIE KAMIENNEJ','CMENTARZYSKO CIAŁOPALNE PŁASKIE GROBY W OBSTAWIE KAMIENNEJ','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03W','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','GROBY WARSTWOWE','CMENTARZYSKO CIAŁOPALNE PŁASKIE GROBY WARSTWOWE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL03I','S','CMENTARZYSKO CIAŁOPALNE','PŁASKIE','INNE','CMENTARZYSKO CIAŁOPALNE PŁASKIE INNE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SL04','S','CMENTARZYSKO CIAŁOPALNE','INNE',NULL,'CMENTARZYSKO CIAŁOPALNE INNE','CM. CIA.');
INSERT INTO "funkcje" VALUES('SG','S','GRÓB',NULL,NULL,'GRÓB','GRÓB');
INSERT INTO "funkcje" VALUES('SG01B','S','GRÓB','KURHAN','BEZ NASYPU','GRÓB KURHAN  BEZ NASYPU','GRÓB');
INSERT INTO "funkcje" VALUES('SG01K','S','GRÓB','KURHAN','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB KURHAN  Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','GRÓB');
INSERT INTO "funkcje" VALUES('SG01P','S','GRÓB','KURHAN','Z PŁASZCZEM KAMIENNYM','GRÓB KURHAN  Z PŁASZCZEM KAMIENNYM','GRÓB');
INSERT INTO "funkcje" VALUES('SG01N','S','GRÓB','KURHAN','Z ZACHOWANYM NASYPEM','GRÓB KURHAN  Z ZACHOWANYM NASYPEM','GRÓB');
INSERT INTO "funkcje" VALUES('SG02','S','GRÓB','MEGAKSYLON',NULL,'GRÓB MEGAKSYLON','GRÓB');
INSERT INTO "funkcje" VALUES('SG03D','S','GRÓB','MEGALIT','DOLMEN','GRÓB MEGALIT DOLMEN','GRÓB');
INSERT INTO "funkcje" VALUES('SG03G','S','GRÓB','MEGALIT','GALERIOWY','GRÓB MEGALIT GALERIOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG03O','S','GRÓB','MEGALIT','KORYTARZOWY','GRÓB MEGALIT KORYTARZOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG03Q','S','GRÓB','MEGALIT','QUASI-MEGALIT','GRÓB MEGALIT QUASI-MEGALIT','GRÓB');
INSERT INTO "funkcje" VALUES('SG03S','S','GRÓB','MEGALIT','SKRZYNKOWY','GRÓB MEGALIT SKRZYNKOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG03U','S','GRÓB','MEGALIT','TYPU KUJAWSKIEGO','GRÓB MEGALIT TYPU KUJAWSKIEGO','GRÓB');
INSERT INTO "funkcje" VALUES('SG04','S','GRÓB','NISZOWY/ KATAKUMBOWY',NULL,'GRÓB NISZOWY/ KATAKUMBOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG05J','S','GRÓB','PŁASKI','JAMOWY','GRÓB PŁASKI JAMOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG05P','S','GRÓB','PŁASKI','POPIELNICOWY','GRÓB PŁASKI POPIELNICOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG05S','S','GRÓB','PŁASKI','SKRZYNKOWY','GRÓB PŁASKI SKRZYNKOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG05K','S','GRÓB','PŁASKI','W OBSTAWIE KAMIENNEJ','GRÓB PŁASKI W OBSTAWIE KAMIENNEJ','GRÓB');
INSERT INTO "funkcje" VALUES('SG05W','S','GRÓB','PŁASKI','WARSTWOWY','GRÓB PŁASKI WARSTWOWY','GRÓB');
INSERT INTO "funkcje" VALUES('SG05I','S','GRÓB','PŁASKI','INNY','GRÓB PŁASKI INNY','GRÓB');
INSERT INTO "funkcje" VALUES('SG06','S','GRÓB','INNY',NULL,'GRÓB INNY','GRÓB');
INSERT INTO "funkcje" VALUES('SC','S','CMENTARZYSKO',NULL,NULL,'CMENTARZYSKO','CMENT.');
INSERT INTO "funkcje" VALUES('SC01B','S','CMENTARZYSKO','KURHANOWE','BEZ NASYPÓW','CMENTARZYSKO KURHANOWE BEZ NASYPÓW','CMENT.');
INSERT INTO "funkcje" VALUES('SC01K','S','CMENTARZYSKO','KURHANOWE','Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CMENTARZYSKO KURHANOWE Z KONSTRUKCJAMI KAMIENNYMI W CZĘŚCI PŁASKIEJ (KRĘGI, BRUKI)','CMENT.');
INSERT INTO "funkcje" VALUES('SC01P','S','CMENTARZYSKO','KURHANOWE','Z PŁASZCZEM KAMIENNYM','CMENTARZYSKO KURHANOWE Z PŁASZCZEM KAMIENNYM','CMENT.');
INSERT INTO "funkcje" VALUES('SC01N','S','CMENTARZYSKO','KURHANOWE','Z ZACHOWANYMI NASYPAMI','CMENTARZYSKO KURHANOWE Z ZACHOWANYMI NASYPAMI','CMENT.');
INSERT INTO "funkcje" VALUES('SC02D','S','CMENTARZYSKO','MEGALITYCZNE','DOLMENY','CMENTARZYSKO MEGALITYCZNE DOLMENY','CMENT.');
INSERT INTO "funkcje" VALUES('SC02G','S','CMENTARZYSKO','MEGALITYCZNE','MEGALITY GALERIOWE','CMENTARZYSKO MEGALITYCZNE MEGALITY GALERIOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC02O','S','CMENTARZYSKO','MEGALITYCZNE','MEGALITY KORYTARZOWE','CMENTARZYSKO MEGALITYCZNE MEGALITY KORYTARZOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC02S','S','CMENTARZYSKO','MEGALITYCZNE','MEGALITY SKRZYNKOWE','CMENTARZYSKO MEGALITYCZNE MEGALITY SKRZYNKOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC02U','S','CMENTARZYSKO','MEGALITYCZNE','MEGALITY TYPU KUJAWSKIEGO','CMENTARZYSKO MEGALITYCZNE MEGALITY TYPU KUJAWSKIEGO','CMENT.');
INSERT INTO "funkcje" VALUES('SC02Q','S','CMENTARZYSKO','MEGALITYCZNE','QUASI-MEGALITY','CMENTARZYSKO MEGALITYCZNE QUASI-MEGALITY','CMENT.');
INSERT INTO "funkcje" VALUES('SC03J','S','CMENTARZYSKO','PŁASKIE','GROBY JAMOWE','CMENTARZYSKO PŁASKIE GROBY JAMOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC03P','S','CMENTARZYSKO','PŁASKIE','GROBY POPIELNICOWE','CMENTARZYSKO PŁASKIE GROBY POPIELNICOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC03S','S','CMENTARZYSKO','PŁASKIE','GROBY SKRZYNKOWE','CMENTARZYSKO PŁASKIE GROBY SKRZYNKOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC03K','S','CMENTARZYSKO','PŁASKIE','GROBY W OBSTAWIE KAMIENNEJ','CMENTARZYSKO PŁASKIE GROBY W OBSTAWIE KAMIENNEJ','CMENT.');
INSERT INTO "funkcje" VALUES('SC03W','S','CMENTARZYSKO','PŁASKIE','GROBY WARSTWOWE','CMENTARZYSKO PŁASKIE GROBY WARSTWOWE','CMENT.');
INSERT INTO "funkcje" VALUES('SC03I','S','CMENTARZYSKO','PŁASKIE','INNE','CMENTARZYSKO PŁASKIE INNE','CMENT.');
INSERT INTO "funkcje" VALUES('SC04','S','CMENTARZYSKO','INNE',NULL,'CMENTARZYSKO INNE','CMENT.');
INSERT INTO "funkcje" VALUES('SN','S','NIEPOCHOWANE SZCZĄTKI LUDZKIE',NULL,NULL,'NIEPOCHOWANE SZCZĄTKI LUDZKIE','SZCZĄTKI');
INSERT INTO "funkcje" VALUES('G','G',NULL,NULL,NULL,NULL,'GOSP');
INSERT INTO "funkcje" VALUES('GI','G','INFRASTRUKTURA',NULL,NULL,'INFRASTRUKTURA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI01','G','INFRASTRUKTURA','BRÓD',NULL,'INFRASTRUKTURA BRÓD','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI02','G','INFRASTRUKTURA','DROGA',NULL,'INFRASTRUKTURA DROGA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI03','G','INFRASTRUKTURA','FABRYKA',NULL,'INFRASTRUKTURA FABRYKA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI04','G','INFRASTRUKTURA','FALOCHRON',NULL,'INFRASTRUKTURA FALOCHRON','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI05','G','INFRASTRUKTURA','GROBLA',NULL,'INFRASTRUKTURA GROBLA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI06','G','INFRASTRUKTURA','KANAŁ',NULL,'INFRASTRUKTURA KANAŁ','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI07','G','INFRASTRUKTURA','KARCZMA',NULL,'INFRASTRUKTURA KARCZMA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI08','G','INFRASTRUKTURA','LATARNIA',NULL,'INFRASTRUKTURA LATARNIA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI09','G','INFRASTRUKTURA','MOST',NULL,'INFRASTRUKTURA MOST','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI10','G','INFRASTRUKTURA','NABRZEŻE',NULL,'INFRASTRUKTURA NABRZEŻE','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI11','G','INFRASTRUKTURA','POMOST',NULL,'INFRASTRUKTURA POMOST','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI12','G','INFRASTRUKTURA','PORT',NULL,'INFRASTRUKTURA PORT','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI13','G','INFRASTRUKTURA','STUDNIA',NULL,'INFRASTRUKTURA STUDNIA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI14','G','INFRASTRUKTURA','WODOCIĄGI I KANALIZACJA',NULL,'INFRASTRUKTURA WODOCIĄGI I KANALIZACJA','INFRASTR.');
INSERT INTO "funkcje" VALUES('GI15','G','INFRASTRUKTURA','INNE',NULL,'INFRASTRUKTURA INNE','INFRASTR.');
INSERT INTO "funkcje" VALUES('GK','G','KILL SITE',NULL,NULL,'KILL SITE','KILL SITE');
INSERT INTO "funkcje" VALUES('GZ','G','KRALL/ZAGRODA DLA ZWIERZĄT',NULL,NULL,'KRALL/ZAGRODA DLA ZWIERZĄT','KRALL');
INSERT INTO "funkcje" VALUES('GE','G','MIEJSCE EKSPLOATACJI SUROWCA',NULL,NULL,'MIEJSCE EKSPLOATACJI SUROWCA','MIEJ. EKSP.');
INSERT INTO "funkcje" VALUES('GE01','G','MIEJSCE EKSPLOATACJI SUROWCA','GLINIANKA',NULL,'MIEJSCE EKSPLOATACJI SUROWCA GLINIANKA','MIEJ. EKSP.');
INSERT INTO "funkcje" VALUES('GE02','G','MIEJSCE EKSPLOATACJI SUROWCA','KOPALNIA',NULL,'MIEJSCE EKSPLOATACJI SUROWCA KOPALNIA','MIEJ. EKSP.');
INSERT INTO "funkcje" VALUES('GE03','G','MIEJSCE EKSPLOATACJI SUROWCA','KOPALNIA KRZEMIENIA',NULL,'MIEJSCE EKSPLOATACJI SUROWCA KOPALNIA KRZEMIENIA','MIEJ. EKSP.');
INSERT INTO "funkcje" VALUES('GE04','G','MIEJSCE EKSPLOATACJI SUROWCA','INNE',NULL,'MIEJSCE EKSPLOATACJI SUROWCA INNE','MIEJ. EKSP.');
INSERT INTO "funkcje" VALUES('GP','G','MIEJSCE PRODUKCJI',NULL,NULL,'MIEJSCE PRODUKCJI','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP01','G','MIEJSCE PRODUKCJI','BROWAR',NULL,'MIEJSCE PRODUKCJI BROWAR','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP02','G','MIEJSCE PRODUKCJI','DYMARKI',NULL,'MIEJSCE PRODUKCJI DYMARKI','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP03','G','MIEJSCE PRODUKCJI','GARBARNIA',NULL,'MIEJSCE PRODUKCJI GARBARNIA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP04','G','MIEJSCE PRODUKCJI','GARNCARNIA',NULL,'MIEJSCE PRODUKCJI GARNCARNIA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP05','G','MIEJSCE PRODUKCJI','GORZELNIA',NULL,'MIEJSCE PRODUKCJI GORZELNIA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP06','G','MIEJSCE PRODUKCJI','HUTA',NULL,'MIEJSCE PRODUKCJI HUTA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP07','G','MIEJSCE PRODUKCJI','KRZEMIENICA',NULL,'MIEJSCE PRODUKCJI KRZEMIENICA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP08','G','MIEJSCE PRODUKCJI','KUŹNIA',NULL,'MIEJSCE PRODUKCJI KUŹNIA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP09','G','MIEJSCE PRODUKCJI','MANUFAKTURA',NULL,'MIEJSCE PRODUKCJI MANUFAKTURA','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP10','G','MIEJSCE PRODUKCJI','MIEJSCE OBRÓBKI SUROWCÓW',NULL,'MIEJSCE PRODUKCJI MIEJSCE OBRÓBKI SUROWCÓW','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP11','G','MIEJSCE PRODUKCJI','MIELERZ',NULL,'MIEJSCE PRODUKCJI MIELERZ','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP12','G','MIEJSCE PRODUKCJI','MŁYN',NULL,'MIEJSCE PRODUKCJI MŁYN','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP13','G','MIEJSCE PRODUKCJI','PIECOWISKO',NULL,'MIEJSCE PRODUKCJI PIECOWISKO','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP14','G','MIEJSCE PRODUKCJI','WARSZTAT RZEMIEŚLNICZY',NULL,'MIEJSCE PRODUKCJI WARSZTAT RZEMIEŚLNICZY','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GP15','G','MIEJSCE PRODUKCJI','INNE',NULL,'MIEJSCE PRODUKCJI INNE','MIEJ. PROD');
INSERT INTO "funkcje" VALUES('GS01','G','ŚMIETNISKO',NULL,NULL,'ŚMIETNISKO','ŚMIET.');
INSERT INTO "funkcje" VALUES('GM01','G','ŚMIETNISKO MUSZLOWE',NULL,NULL,'ŚMIETNISKO MUSZLOWE','ŚMIET MUSZ.');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE gminy(id integer primary key, start varchar(2) not null, nazwa varchar(50));
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE jednostki(kod varchar(6) primary key, okres varchar(1), czlon1 varchar(30), czlon2 varchar(30), nazwa varchar(30), skrot varchar(15), start varchar(2));
INSERT INTO "jednostki" VALUES('P','P',NULL,NULL,'P','P','KA');
INSERT INTO "jednostki" VALUES('PKL','P','TECHNOKOMPLEKS KLAKTOŃSKI',NULL,'TECHNOKOMPLEKS KLAKTOŃSKI','TK. KLAKTOŃS.','KL');
INSERT INTO "jednostki" VALUES('PKL01','P','TECHNOKOMPLEKS KLAKTOŃSKI','KULTURA KLAKTOŃSKA','KULTURA KLAKTOŃSKA','KUL. KLAKTOŃS.','KL');
INSERT INTO "jednostki" VALUES('PKL02','P','TECHNOKOMPLEKS KLAKTOŃSKI','KULTURA TAJACKA','KULTURA TAJACKA','KUL. TAJACKA.','TA');
INSERT INTO "jednostki" VALUES(NULL,'P','TECHNOKOMPLEKS MAGDALEŃSKI',NULL,'TECHNOKOMPLEKS MAGDALEŃSKI','TK. MAGDALEŃ.','MA');
INSERT INTO "jednostki" VALUES('PMG01','P','TECHNOKOMPLEKS MAGDALEŃSKI','KULTURA MADLEŃSKA','KULTURA MADLEŃSKA','KUL. MADLEŃSK.','MA');
INSERT INTO "jednostki" VALUES('PMG02','P','TECHNOKOMPLEKS MAGDALEŃSKI','KULTURA MAGDALEŃSKA','KULTURA MAGDALEŃSKA','KUL. MAGDALEŃ.','MA');
INSERT INTO "jednostki" VALUES('PMG03','P','TECHNOKOMPLEKS MAGDALEŃSKI','KULTURA MAGDALEŃSKA ŚRODKOWA','KULTURA MAGDALEŃSKA ŚRODKOWA','KUL. MAGD. ŚROD.','MA');
INSERT INTO "jednostki" VALUES('PMG04','P','TECHNOKOMPLEKS MAGDALEŃSKI','KULTURA MAGDALEŃSKA PÓŹNA','KULTURA MAGDALEŃSKA PÓŹNA','KUL. MAGD. PÓŹN.','MA');
INSERT INTO "jednostki" VALUES('PMI','P','TECHNOKOMPLEKS MIKROLITYCZNY',NULL,'TECHNOKOMPLEKS MIKROLITYCZNY','TK. MIKROLIT.','MI');
INSERT INTO "jednostki" VALUES('POR','P','TECHNOKOMPLEKS ORYNIACKI',NULL,'TECHNOKOMPLEKS ORYNIACKI','TK. ORYNIACK.','OR');
INSERT INTO "jednostki" VALUES('POR01','P','TECHNOKOMPLEKS ORYNIACKI','KULTURA KREMS-DUFOUR','KULTURA KREMS-DUFOUR','KUL. KREM.-DUFO.','KR');
INSERT INTO "jednostki" VALUES('POR02','P','TECHNOKOMPLEKS ORYNIACKI','KULTURA OLSZEWSKA','KULTURA OLSZEWSKA','KUL. OLSZEWSK.','OL');
INSERT INTO "jednostki" VALUES('POR03','P','TECHNOKOMPLEKS ORYNIACKI','KULTURA ORYNIACKA','KULTURA ORYNIACKA','KUL. ORYNIACK.','OR');
INSERT INTO "jednostki" VALUES('POR04','P','TECHNOKOMPLEKS ORYNIACKI','ZESPOŁY TYPU PIEKARY II','ZESPOŁY TYPU PIEKARY II','ZESP. TYPU. PIEK.','TY');
INSERT INTO "jednostki" VALUES('POR05','P','TECHNOKOMPLEKS ORYNIACKI','ZESPOŁY TYPU SOWINIEC','ZESPOŁY TYPU SOWINIEC','ZESP. TYPU. SOWI.','TY');
INSERT INTO "jednostki" VALUES('POR06','P','TECHNOKOMPLEKS ORYNIACKI','KULTURA ZWIERZYNIECKA','KULTURA ZWIERZYNIECKA','KUL. ZWIERZYN.','ZW');
INSERT INTO "jednostki" VALUES('PPW','P','TECHNOKOMPLEKS PÓŁNOCNO-WSCHODNI',NULL,'TECHNOKOMPLEKS PÓŁNOCNO-WSCHODNI','TK. PÓŁN.-WSCH.','PÓ');
INSERT INTO "jednostki" VALUES('PPW01','P','TECHNOKOMPLEKS PÓŁNOCNO-WSCHODNI','KULTURA KUNDAJSKA','KULTURA KUNDAJSKA','KUL. KUNDAJSK.','KU');
INSERT INTO "jednostki" VALUES('PPW02','P','TECHNOKOMPLEKS PÓŁNOCNO-WSCHODNI','KULTURA NIEMEŃSKA','KULTURA NIEMEŃSKA','KUL. NIEMEŃSK.','NI');
INSERT INTO "jednostki" VALUES('PTR','P','TECHNOKOMPLEKS TARDIGRAWECKI',NULL,'TECHNOKOMPLEKS TARDIGRAWECKI','TK. TARDIGRA.','TA');
INSERT INTO "jednostki" VALUES('PTR01','P','TECHNOKOMPLEKS TARDIGRAWECKI','KULTURA WITOWSKA','KULTURA WITOWSKA','KUL. WITOWSKA.','WI');
INSERT INTO "jednostki" VALUES('PTA','P','TECHNOKOMPLEKS TARNOWIAŃSKI',NULL,'TECHNOKOMPLEKS TARNOWIAŃSKI','TK. TARNOWIA.','TA');
INSERT INTO "jednostki" VALUES('PTA01','P','TECHNOKOMPLEKS TARNOWIAŃSKI','KULTURA FEDERMESSER','KULTURA FEDERMESSER','KUL. FEDERMES.','FE');
INSERT INTO "jednostki" VALUES('PTA02','P','TECHNOKOMPLEKS TARNOWIAŃSKI','KULTURA TARNOWSKA','KULTURA TARNOWSKA','KUL. TARNOWSK.','TA');
INSERT INTO "jednostki" VALUES('PTA03','P','TECHNOKOMPLEKS TARNOWIAŃSKI','GRUPA WITOWSKA','GRUPA WITOWSKA','GR. WITOWSKA.','WI');
INSERT INTO "jednostki" VALUES('PJE','P','TECHNOKOMPLEKS Z JEDNOZADZIORCAMI',NULL,'TECHNOKOMPLEKS Z JEDNOZADZIORCAMI','TK. Z. JEDN.','Z.');
INSERT INTO "jednostki" VALUES('PJE01','P','TECHNOKOMPLEKS Z JEDNOZADZIORCAMI','KULTURA HAMBURSKA','KULTURA HAMBURSKA','KUL. HAMBURSK.','HA');
INSERT INTO "jednostki" VALUES('PLI','P','TECHNOKOMPLEKS Z LIŚCIAKAMI',NULL,'TECHNOKOMPLEKS Z LIŚCIAKAMI','TK. Z. LIŚC.','Z.');
INSERT INTO "jednostki" VALUES('PLI01','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA AHRENSBURSKA','KULTURA AHRENSBURSKA','KUL. AHRENSBU.','AH');
INSERT INTO "jednostki" VALUES('PLI02','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA BROMME','KULTURA BROMME','KUL. BROMME.','BR');
INSERT INTO "jednostki" VALUES('PLI03','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','CYKL MAZOWSZAŃSKI','CYKL MAZOWSZAŃSKI','CYKL MAZOWSZA.','MA');
INSERT INTO "jednostki" VALUES('PLI04','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA DESNEŃSKA','KULTURA DESNEŃSKA','KUL. DESNEŃSK.','DE');
INSERT INTO "jednostki" VALUES('PLI05','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA GREŃSKO-ŚWIDERSKA','KULTURA GREŃSKO-ŚWIDERSKA','KUL. GREŃ.-ŚWID.','GR');
INSERT INTO "jednostki" VALUES('PLI06','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA LYNGBIJSKA','KULTURA LYNGBIJSKA','KUL. LYNGBIJS.','LY');
INSERT INTO "jednostki" VALUES('PLI07','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA LYNGBY-BROMME','KULTURA LYNGBY-BROMME','KUL. LYNG.-BROM.','LY');
INSERT INTO "jednostki" VALUES('PLI08','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','PRZEMYSŁ CHWALIBOGOWICKI','PRZEMYSŁ CHWALIBOGOWICKI','PRZEM. CHWALIBO.','CH');
INSERT INTO "jednostki" VALUES('PLI09','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','PRZEMYSŁ NOWOMŁYŃSKI','PRZEMYSŁ NOWOMŁYŃSKI','PRZEM. NOWOMŁYŃ.','NO');
INSERT INTO "jednostki" VALUES('PLI10','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','PRZEMYSŁ ŚWIDERSKI','PRZEMYSŁ ŚWIDERSKI','PRZEM. ŚWIDERSK.','ŚW');
INSERT INTO "jednostki" VALUES('PLI11','P','TECHNOKOMPLEKS Z LIŚCIAKAMI','KULTURA ŚWIDERSKA','KULTURA ŚWIDERSKA','KUL. ŚWIDERSK.','ŚW');
INSERT INTO "jednostki" VALUES('PBI','P','TECHNOKOMPLEKS Z NARZĘDZIAMI BIFACJALNYMI',NULL,'TECHNOKOMPLEKS Z NARZĘDZIAMI BIFACJALNYMI','TK. Z. NARZ.','Z.');
INSERT INTO "jednostki" VALUES('PNO','P','TECHNOKOMPLEKS Z NOŻAMI I PIĘŚCIAKAMI',NULL,'TECHNOKOMPLEKS Z NOŻAMI I PIĘŚCIAKAMI','TK. Z. NOŻA.','Z.');
INSERT INTO "jednostki" VALUES('POS','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI',NULL,'TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','TK. Z. OSTR.','Z.');
INSERT INTO "jednostki" VALUES('POS01','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA BOHUNICKA','KULTURA BOHUNICKA','KUL. BOHUNICK.','BO');
INSERT INTO "jednostki" VALUES('POS02','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA JERZMANOWICKA','KULTURA JERZMANOWICKA','KUL. JERZMANO.','JE');
INSERT INTO "jednostki" VALUES('POS03','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA JERZMANOWICKO-TELMAŃSKA','KULTURA JERZMANOWICKO-TELMAŃSKA','KUL. JERZ.-TELM.','JE');
INSERT INTO "jednostki" VALUES('POS04','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA PRESELECKA','KULTURA PRESELECKA','KUL. PRESELEC.','PR');
INSERT INTO "jednostki" VALUES('POS05','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA SELECKA','KULTURA SELECKA','KUL. SELECKA.','SE');
INSERT INTO "jednostki" VALUES('POS06','P','TECHNOKOMPLEKS Z OSTRZAMI LIŚCIOWATYMI','KULTURA SZELECKA','KULTURA SZELECKA','KUL. SZELECKA.','SZ');
INSERT INTO "jednostki" VALUES('PPI','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI',NULL,'TECHNOKOMPLEKS Z PIĘŚCIAKAMI','TK. Z. PIĘŚ.','Z.');
INSERT INTO "jednostki" VALUES('PPI01','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','KULTURA ASZELSKA','KULTURA ASZELSKA','KUL. ASZELSKA.','AS');
INSERT INTO "jednostki" VALUES('PPI02','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','CYKL PRĄDNICKI','CYKL PRĄDNICKI','CYKL PRĄDNICK.','PR');
INSERT INTO "jednostki" VALUES('PPI03','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','KULTURA MIKOCKA','KULTURA MIKOCKA','KUL. MIKOCKA.','MI');
INSERT INTO "jednostki" VALUES('PPI04','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','KULTURA MIKOCKO-PRĄDNICKA','KULTURA MIKOCKO-PRĄDNICKA','KUL. MIKO.-PRĄD.','MI');
INSERT INTO "jednostki" VALUES('PPI05','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','ZESPÓŁ TYPU BOCKSTEIN','ZESPÓŁ TYPU BOCKSTEIN','ZESP. TYPU. BOCK.','TY');
INSERT INTO "jednostki" VALUES('PPI06','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','ZESPÓŁ TYPU CIEMNA','ZESPÓŁ TYPU CIEMNA','ZESP. TYPU. CIEM.','TY');
INSERT INTO "jednostki" VALUES('PPI07','P','TECHNOKOMPLEKS Z PIĘŚCIAKAMI','ZESPÓŁ TYPU WYLOTNE','ZESPÓŁ TYPU WYLOTNE','ZESP. TYPU. WYLO.','TY');
INSERT INTO "jednostki" VALUES('PTY','P','TECHNOKOMPLEKS Z TYLCZAKAMI',NULL,'TECHNOKOMPLEKS Z TYLCZAKAMI','TK. Z. TYLC.','Z.');
INSERT INTO "jednostki" VALUES('PTY01','P','TECHNOKOMPLEKS Z TYLCZAKAMI','KULTURA GRAWECKA','KULTURA GRAWECKA','KUL. GRAWECKA.','GR');
INSERT INTO "jednostki" VALUES('PTY02','P','TECHNOKOMPLEKS Z TYLCZAKAMI','KULTURA KOSTIENKOWSKO-AWDIEJEWSKA','KULTURA KOSTIENKOWSKO-AWDIEJEWSKA','KUL. KOST.-AWDI.','KO');
INSERT INTO "jednostki" VALUES('PTY03','P','TECHNOKOMPLEKS Z TYLCZAKAMI','KULTURA MOŁODOWSKA','KULTURA MOŁODOWSKA','KUL. MOŁODOWS.','MO');
INSERT INTO "jednostki" VALUES('PTY04','P','TECHNOKOMPLEKS Z TYLCZAKAMI','KULTURA PAVLOVSKA','KULTURA PAVLOVSKA','KUL. PAVLOVSK.','PA');
INSERT INTO "jednostki" VALUES('PTY05','P','TECHNOKOMPLEKS Z TYLCZAKAMI','KULTURA WSCHODNIOGRAWECKA','KULTURA WSCHODNIOGRAWECKA','KUL. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('PTY06','P','TECHNOKOMPLEKS Z TYLCZAKAMI','ZESPÓŁ TYPU MAMUTOWA','ZESPÓŁ TYPU MAMUTOWA','ZESP. TYPU. MAMU.','TY');
INSERT INTO "jednostki" VALUES('PLU','P','TECHNOKOMPLEKS Z TYLCZAKAMI ŁUKOWYMI',NULL,'TECHNOKOMPLEKS Z TYLCZAKAMI ŁUKOWYMI','TK. Z. TYLC.','Z.');
INSERT INTO "jednostki" VALUES('PLU01','P','TECHNOKOMPLEKS Z TYLCZAKAMI ŁUKOWYMI','KULTURA FEDERMESSER','KULTURA FEDERMESSER','KUL. FEDERMES.','FE');
INSERT INTO "jednostki" VALUES('PLU02','P','TECHNOKOMPLEKS Z TYLCZAKAMI ŁUKOWYMI','KULTURA TARNOWSKA','KULTURA TARNOWSKA','KUL. TARNOWSK.','TA');
INSERT INTO "jednostki" VALUES('PLU03','P','TECHNOKOMPLEKS Z TYLCZAKAMI ŁUKOWYMI','KULTURA WITOWSKA','KULTURA WITOWSKA','KUL. WITOWSKA.','WI');
INSERT INTO "jednostki" VALUES('M','M',NULL,NULL,'M','M','KA');
INSERT INTO "jednostki" VALUES('MPN','M','TECHNOKOMPLEKS PÓŁNOCNY',NULL,'TECHNOKOMPLEKS PÓŁNOCNY','TK. PÓŁNOCNY.','PÓ');
INSERT INTO "jednostki" VALUES('MPN01','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA CHOJNICKO-PIEŃKOWSKA','KULTURA CHOJNICKO-PIEŃKOWSKA','KUL. CHOJ.-PIEŃ.','CH');
INSERT INTO "jednostki" VALUES('MPN02','M','TECHNOKOMPLEKS PÓŁNOCNY','CYKL NARWIAŃSKI','CYKL NARWIAŃSKI','CYKL NARWIAŃS.','NA');
INSERT INTO "jednostki" VALUES('MPN03','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA DUVENSEE','KULTURA DUVENSEE','KUL. DUVENSEE.','DU');
INSERT INTO "jednostki" VALUES('MPN04','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA KOMORNICA-DUVENSEE','KULTURA KOMORNICA-DUVENSEE','KUL. KOMO.-DUVE.','KO');
INSERT INTO "jednostki" VALUES('MPN05','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA KOMORNICKA','KULTURA KOMORNICKA','KUL. KOMORNIC.','KO');
INSERT INTO "jednostki" VALUES('MPN06','M','TECHNOKOMPLEKS PÓŁNOCNY','KOMPLEKS DUVENSEE','KOMPLEKS DUVENSEE','KOMPLEKS DUVENSEE','DU');
INSERT INTO "jednostki" VALUES('MPN07','M','TECHNOKOMPLEKS PÓŁNOCNY','KOMPLEKS MAGLEMOSE','KOMPLEKS MAGLEMOSE','KOMPLEKS MAGLEMOSE','MA');
INSERT INTO "jednostki" VALUES('MPN08','M','TECHNOKOMPLEKS PÓŁNOCNY','KOMPLEKS POSTMAGLEMOSKI','KOMPLEKS POSTMAGLEMOSKI','KOMPLEKS POSTMAGLEMOSKI','PO');
INSERT INTO "jednostki" VALUES('MPN09','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA OLDESLOE','KULTURA OLDESLOE','KUL. OLDESLOE.','OL');
INSERT INTO "jednostki" VALUES('MPN10','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA PROTOKOMORNICKA','KULTURA PROTOKOMORNICKA','KUL. PROTOKOM.','PR');
INSERT INTO "jednostki" VALUES('MPN11','M','TECHNOKOMPLEKS PÓŁNOCNY','KULTURA SVAERDBORG','KULTURA SVAERDBORG','KUL. SVAERDBO.','SV');
INSERT INTO "jednostki" VALUES('MZA','M','TECHNOKOMPLEKS ZACHODNI',NULL,'TECHNOKOMPLEKS ZACHODNI','TK. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('MZA01','M','TECHNOKOMPLEKS ZACHODNI','KULTURA BEUROŃSKA','KULTURA BEUROŃSKA','KUL. BEUROŃSK.','BE');
INSERT INTO "jednostki" VALUES('MZA02','M','TECHNOKOMPLEKS ZACHODNI','KULTURA BEUROUN-COINCY','KULTURA BEUROUN-COINCY','KUL. BEUR.-COIN.','BE');
INSERT INTO "jednostki" VALUES('MZA03','M','TECHNOKOMPLEKS ZACHODNI','KULTURA TARDENUASKA','KULTURA TARDENUASKA','KUL. TARDENUA.','TA');
INSERT INTO "jednostki" VALUES('MWI','M','CYKL WIŚLANSKI',NULL,'CYKL WIŚLANSKI','CYKL WIŚL. .','WI');
INSERT INTO "jednostki" VALUES('MJA','M','KULTURA JANISŁAWICKA',NULL,'KULTURA JANISŁAWICKA','KUL. JANI. .','JA');
INSERT INTO "jednostki" VALUES('MJA01','M','KULTURA JANISŁAWICKA','GRUPA WISTECKA','GRUPA WISTECKA','GR. WISTECKA.','WI');
INSERT INTO "jednostki" VALUES('MJA02','M','KULTURA JANISŁAWICKA','GRUPA WSCHODNIA','GRUPA WSCHODNIA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('L','L',NULL,NULL,'L','L','KA');
INSERT INTO "jednostki" VALUES('LBO','L','GRUPA BOBRZAŃSKA',NULL,'GRUPA BOBRZAŃSKA','GR. BOBRZAŃS.','BO');
INSERT INTO "jednostki" VALUES('LZA','L','TECHNOKOMPLEKS ZACHODNI',NULL,'TECHNOKOMPLEKS ZACHODNI','TK. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('LZA01','L','TECHNOKOMPLEKS ZACHODNI','KULTURA ERTEBØLLE','KULTURA ERTEBØLLE','KUL. ERTEBØLL.','ER');
INSERT INTO "jednostki" VALUES('LZA02','L','TECHNOKOMPLEKS ZACHODNI','KULTURA ERTEBØLLE-ELLERBEK','KULTURA ERTEBØLLE-ELLERBEK','KUL. ERTE.-ELLE.','ER');
INSERT INTO "jednostki" VALUES('LCI','L','ZESPOŁY TYPU CIOŁKI',NULL,'ZESPOŁY TYPU CIOŁKI','ZESP. TYPU. CIOŁ.','TY');
INSERT INTO "jednostki" VALUES('LKO','L','ZESPOŁY TYPU KOLANKOWO',NULL,'ZESPOŁY TYPU KOLANKOWO','ZESP. TYPU. KOLA.','TY');
INSERT INTO "jednostki" VALUES('LTA','L','ZESPOŁY TYPU TANOWO',NULL,'ZESPOŁY TYPU TANOWO','ZESP. TYPU. TANO.','TY');
INSERT INTO "jednostki" VALUES('N','N',NULL,NULL,'N','N','KA');
INSERT INTO "jednostki" VALUES('NAK','N','KULTURA AMFOR KULISTYCH',NULL,'KULTURA AMFOR KULISTYCH','KUL. AMFO. KULI.','AM');
INSERT INTO "jednostki" VALUES('NAK01','N','KULTURA AMFOR KULISTYCH','GRUPA HRUBIESZOWSKA','GRUPA HRUBIESZOWSKA','GR. HRUBIESZ.','HR');
INSERT INTO "jednostki" VALUES('NAK02','N','KULTURA AMFOR KULISTYCH','GRUPA KIELECKA','GRUPA KIELECKA','GR. KIELECKA.','KI');
INSERT INTO "jednostki" VALUES('NAK03','N','KULTURA AMFOR KULISTYCH','GRUPA LUBELSKA','GRUPA LUBELSKA','GR. LUBELSKA.','LU');
INSERT INTO "jednostki" VALUES('NAK04','N','KULTURA AMFOR KULISTYCH','GRUPA MAŁOPOLSKA','GRUPA MAŁOPOLSKA','GR. MAŁOPOLS.','MA');
INSERT INTO "jednostki" VALUES('NAK05','N','KULTURA AMFOR KULISTYCH','GRUPA MAZOWIECKO-LUBELSKA','GRUPA MAZOWIECKO-LUBELSKA','GR. MAZO.-LUBE.','MA');
INSERT INTO "jednostki" VALUES('NAK06','N','KULTURA AMFOR KULISTYCH','GRUPA MAZOWIECKO-PODLASKA','GRUPA MAZOWIECKO-PODLASKA','GR. MAZO.-PODL.','MA');
INSERT INTO "jednostki" VALUES('NAK07','N','KULTURA AMFOR KULISTYCH','GRUPA MAZURSKO-WARMIŃSKA','GRUPA MAZURSKO-WARMIŃSKA','GR. MAZU.-WARM.','MA');
INSERT INTO "jednostki" VALUES('NAK08','N','KULTURA AMFOR KULISTYCH','GRUPA POLSKA','GRUPA POLSKA','GR. POLSKA.','PO');
INSERT INTO "jednostki" VALUES('NAK09','N','KULTURA AMFOR KULISTYCH','GRUPA PUŁAWSKA','GRUPA PUŁAWSKA','GR. PUŁAWSKA.','PU');
INSERT INTO "jednostki" VALUES('NAK10','N','KULTURA AMFOR KULISTYCH','GRUPA SANDOMIERSKO-OPATOWSKA','GRUPA SANDOMIERSKO-OPATOWSKA','GR. SAND.-OPAT.','SA');
INSERT INTO "jednostki" VALUES('NAK11','N','KULTURA AMFOR KULISTYCH','GRUPA ŚLĄSKA','GRUPA ŚLĄSKA','GR. ŚLĄSKA.','ŚL');
INSERT INTO "jednostki" VALUES('NAK12','N','KULTURA AMFOR KULISTYCH','GRUPA WIELKOPOLSKO-KUJAWSKA','GRUPA WIELKOPOLSKO-KUJAWSKA','GR. WIEL.-KUJA.','WI');
INSERT INTO "jednostki" VALUES('NAK13','N','KULTURA AMFOR KULISTYCH','GRUPA WOŁYŃSKA','GRUPA WOŁYŃSKA','GR. WOŁYŃSKA.','WO');
INSERT INTO "jednostki" VALUES('NAK14','N','KULTURA AMFOR KULISTYCH','GRUPA WSCHODNIA','GRUPA WSCHODNIA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('NAK15','N','KULTURA AMFOR KULISTYCH','GRUPA WSCHODNIOLUBELSKA','GRUPA WSCHODNIOLUBELSKA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('NAK16','N','KULTURA AMFOR KULISTYCH','GRUPA ZACHODNIA','GRUPA ZACHODNIA','GR. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('NAK17','N','KULTURA AMFOR KULISTYCH','GRUPA ZACHODNIOPOMORSKA','GRUPA ZACHODNIOPOMORSKA','GR. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('NAF','N','KULTURA ARKTYCZNO-FIŃSKA',NULL,'KULTURA ARKTYCZNO-FIŃSKA','KUL. ARKT.-FIŃS.','AR');
INSERT INTO "jednostki" VALUES('NBA','N','KULTURA BADEŃSKA',NULL,'KULTURA BADEŃSKA','KUL. BADEŃSKA.','BA');
INSERT INTO "jednostki" VALUES('NBA01','N','KULTURA BADEŃSKA','GRUPA MOGILSKA','GRUPA MOGILSKA','GR. MOGILSKA.','MO');
INSERT INTO "jednostki" VALUES('NBA02','N','KULTURA BADEŃSKA','GRUPA WYCIĄŻE-KSIĄŻNICE','GRUPA WYCIĄŻE-KSIĄŻNICE','GR. WYCI.-KSIĄ.','WY');
INSERT INTO "jednostki" VALUES('NBA03','N','KULTURA BADEŃSKA','GRUPA ZESŁAWICKO-PLESZOWSKA','GRUPA ZESŁAWICKO-PLESZOWSKA','GR. ZESŁ.-PLES.','ZE');
INSERT INTO "jednostki" VALUES('NBL','N','KULTURA BAŁTYCKA',NULL,'KULTURA BAŁTYCKA','KUL. BAŁTYCKA.','BA');
INSERT INTO "jednostki" VALUES('NBE','N','KULTURA BERNBURSKA',NULL,'KULTURA BERNBURSKA','KUL. BERNBURS.','BE');
INSERT INTO "jednostki" VALUES('NBD','N','KULTURA BODROGKERESZTURSKA',NULL,'KULTURA BODROGKERESZTURSKA','KUL. BODROGKE.','BO');
INSERT INTO "jednostki" VALUES('NBR','N','KULTURA BRZESKOKUJAWSKA',NULL,'KULTURA BRZESKOKUJAWSKA','KUL. BRZESKOK.','BR');
INSERT INTO "jednostki" VALUES('NCD','N','KULTURA CERAMIKI DOŁKOWO-GRZEBYKOWEJ',NULL,'KULTURA CERAMIKI DOŁKOWO-GRZEBYKOWEJ','KUL. CERA. DOŁK.','CE');
INSERT INTO "jednostki" VALUES('NCG','N','KULTURA CERAMIKI GRZEBYKOWEJ',NULL,'KULTURA CERAMIKI GRZEBYKOWEJ','KUL. CERA. GRZE.','CE');
INSERT INTO "jednostki" VALUES('NCP','N','KULTURA CERAMIKI PROMIENISTEJ',NULL,'KULTURA CERAMIKI PROMIENISTEJ','KUL. CERA. PROM.','CE');
INSERT INTO "jednostki" VALUES('NCP01','N','KULTURA CERAMIKI PROMIENISTEJ','GRUPA MOGILSKA','GRUPA MOGILSKA','GR. MOGILSKA.','MO');
INSERT INTO "jednostki" VALUES('NCP02','N','KULTURA CERAMIKI PROMIENISTEJ','GRUPA WYCIĄŻE-KSIĄŻNICE','GRUPA WYCIĄŻE-KSIĄŻNICE','GR. WYCI.-KSIĄ.','WY');
INSERT INTO "jednostki" VALUES('NCP03','N','KULTURA CERAMIKI PROMIENISTEJ','GRUPA ZESŁAWICKO-PLESZOWSKA','GRUPA ZESŁAWICKO-PLESZOWSKA','GR. ZESŁ.-PLES.','ZE');
INSERT INTO "jednostki" VALUES('NCS','N','KULTURA CERAMIKI SZNUROWEJ',NULL,'KULTURA CERAMIKI SZNUROWEJ','KUL. CERA. SZNU.','CE');
INSERT INTO "jednostki" VALUES('NCS01','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA DOLNOODRZAŃSKA','GRUPA DOLNOODRZAŃSKA','GR. DOLNOODR.','DO');
INSERT INTO "jednostki" VALUES('NCS02','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA KRAKOWSKA','GRUPA KRAKOWSKA','GR. KRAKOWSK.','KR');
INSERT INTO "jednostki" VALUES('NCS03','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA KRAKOWSKO-SANDOMIERSKA','GRUPA KRAKOWSKO-SANDOMIERSKA','GR. KRAK.-SAND.','KR');
INSERT INTO "jednostki" VALUES('NCS04','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA KUJAWSKO-WSCHODNIOWIELKOPOLSKA','GRUPA KUJAWSKO-WSCHODNIOWIELKOPOLSKA','GR. KUJA.-WSCH.','KU');
INSERT INTO "jednostki" VALUES('NCS05','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA KURHANÓW PODKARPACKICH','GRUPA KURHANÓW PODKARPACKICH','GR. KURH. PODK.','KU');
INSERT INTO "jednostki" VALUES('NCS06','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA LUBACZOWSKA','GRUPA LUBACZOWSKA','GR. LUBACZOW.','LU');
INSERT INTO "jednostki" VALUES('NCS07','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA NADODRZAŃSKA','GRUPA NADODRZAŃSKA','GR. NADODRZA.','NA');
INSERT INTO "jednostki" VALUES('NCS08','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA POŁUDNIOWO-WSCHODNIOPOLSKA','GRUPA POŁUDNIOWO-WSCHODNIOPOLSKA','GR. POŁU.-WSCH.','PO');
INSERT INTO "jednostki" VALUES('NCS09','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA ŚLĄSKA','GRUPA ŚLĄSKA','GR. ŚLĄSKA.','ŚL');
INSERT INTO "jednostki" VALUES('NCS10','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA WIELKOPOLSKO-KUJAWSKA','GRUPA WIELKOPOLSKO-KUJAWSKA','GR. WIEL.-KUJA.','WI');
INSERT INTO "jednostki" VALUES('NCS11','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA WIELKOPOLSKO-MAZOWIECKA','GRUPA WIELKOPOLSKO-MAZOWIECKA','GR. WIEL.-MAZO.','WI');
INSERT INTO "jednostki" VALUES('NCS12','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA WKRZAŃSKA','GRUPA WKRZAŃSKA','GR. WKRZAŃSK.','WK');
INSERT INTO "jednostki" VALUES('NCS13','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA ZACHODNIA','GRUPA ZACHODNIA','GR. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('NCS14','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA ZACHODNIOPOLSKO-KUJAWSKA','GRUPA ZACHODNIOPOLSKO-KUJAWSKA','GR. ZACH.-KUJA.','ZA');
INSERT INTO "jednostki" VALUES('NCS15','N','KULTURA CERAMIKI SZNUROWEJ','GRUPA ZŁOCKA','GRUPA ZŁOCKA','GR. ZŁOCKA.','ZŁ');
INSERT INTO "jednostki" VALUES('NCW','N','KULTURA CERAMIKI WSTĘGOWEJ RYTEJ',NULL,'KULTURA CERAMIKI WSTĘGOWEJ RYTEJ','KUL. CERA. WSTĘ.','CE');
INSERT INTO "jednostki" VALUES('NCW01','N','KULTURA CERAMIKI WSTĘGOWEJ RYTEJ','ZESPÓŁ TYPU PODGAJ','ZESPÓŁ TYPU PODGAJ','ZESP. TYPU. PODG.','TY');
INSERT INTO "jednostki" VALUES('NCT','N','KULTURA CUCUTENI-TRIPOLJE',NULL,'KULTURA CUCUTENI-TRIPOLJE','KUL. CUCU.-TRIP.','CU');
INSERT INTO "jednostki" VALUES('NDL','N','KULTURA DNIEPROWSKA-ŁABSKA',NULL,'KULTURA DNIEPROWSKA-ŁABSKA','KUL. DNIE.-ŁABS.','DN');
INSERT INTO "jednostki" VALUES('NDD','N','KULTURA DNIEPRZAŃSKO-DONIECKA',NULL,'KULTURA DNIEPRZAŃSKO-DONIECKA','KUL. DNIE.-DONI.','DN');
INSERT INTO "jednostki" VALUES('NER','N','KULTURA ERTEBØLLE',NULL,'KULTURA ERTEBØLLE','KUL. ERTEBØLL.','ER');
INSERT INTO "jednostki" VALUES('NEE','N','KULTURA ERTEBØLLE-ELLERBEK',NULL,'KULTURA ERTEBØLLE-ELLERBEK','KUL. ERTE.-ELLE.','ER');
INSERT INTO "jednostki" VALUES('NFU','N','KULTURA FIŃSKO-UKRAIŃSKA',NULL,'KULTURA FIŃSKO-UKRAIŃSKA','KUL. FIŃS.-UKRA.','FI');
INSERT INTO "jednostki" VALUES('NGJ','N','KULTURA GROBÓW JAMOWYCH',NULL,'KULTURA GROBÓW JAMOWYCH','KUL. GROB. JAMO.','GR');
INSERT INTO "jednostki" VALUES('NGD','N','KULTURA GROBÓW JEDNOSTKOWYCH',NULL,'KULTURA GROBÓW JEDNOSTKOWYCH','KUL. GROB. JEDN.','GR');
INSERT INTO "jednostki" VALUES('NGD01','N','KULTURA GROBÓW JEDNOSTKOWYCH','GRUPA WKRZAŃSKA','GRUPA WKRZAŃSKA','GR. WKRZAŃSK.','WK');
INSERT INTO "jednostki" VALUES('NGR','N','KULTURA GRZEBYKOWA',NULL,'KULTURA GRZEBYKOWA','KUL. GRZEBYKO.','GR');
INSERT INTO "jednostki" VALUES('NGN','N','KULTURA GRZEBYKOWO-NAKŁUWANA',NULL,'KULTURA GRZEBYKOWO-NAKŁUWANA','KUL. GRZE.-NAKŁ.','GR');
INSERT INTO "jednostki" VALUES('NJA','N','KULTURA JAMOWA',NULL,'KULTURA JAMOWA','KUL. JAMOWA.','JA');
INSERT INTO "jednostki" VALUES('NJO','N','KULTURA JORDANOWSKA',NULL,'KULTURA JORDANOWSKA','KUL. JORDANOW.','JO');
INSERT INTO "jednostki" VALUES('NJS','N','KULTURA JORDANOWSKO-ŚLĄSKA',NULL,'KULTURA JORDANOWSKO-ŚLĄSKA','KUL. JORD.-ŚLĄS.','JO');
INSERT INTO "jednostki" VALUES('NKL','N','KULTURA KŁUTO-LENDZIELSKA',NULL,'KULTURA KŁUTO-LENDZIELSKA','KUL. KŁUT.-LEND.','KŁ');
INSERT INTO "jednostki" VALUES('NLE','N','KULTURA LENDZIELSKA',NULL,'KULTURA LENDZIELSKA','KUL. LENDZIEL.','LE');
INSERT INTO "jednostki" VALUES('NLE01','N','KULTURA LENDZIELSKA','GRUPA BRZESKO-KUJAWSKA','GRUPA BRZESKO-KUJAWSKA','GR. BRZE.-KUJA.','BR');
INSERT INTO "jednostki" VALUES('NLE02','N','KULTURA LENDZIELSKA','GRUPA CERAMIKI BIAŁO-MALOWANEJ','GRUPA CERAMIKI BIAŁO-MALOWANEJ','GR. CERA. BIAŁ.','CE');
INSERT INTO "jednostki" VALUES('NLE03','N','KULTURA LENDZIELSKA','GRUPA GÓRNOŚLĄSKA','GRUPA GÓRNOŚLĄSKA','GR. GÓRNOŚLĄ.','GÓ');
INSERT INTO "jednostki" VALUES('NLE04','N','KULTURA LENDZIELSKA','GRUPA GÓROWSKA','GRUPA GÓROWSKA','GR. GÓROWSKA.','GÓ');
INSERT INTO "jednostki" VALUES('NLE05','N','KULTURA LENDZIELSKA','GRUPA JANÓWECKA','GRUPA JANÓWECKA','GR. JANÓWECK.','JA');
INSERT INTO "jednostki" VALUES('NLE06','N','KULTURA LENDZIELSKA','GRUPA JORDANOWSKA','GRUPA JORDANOWSKA','GR. JORDANOW.','JO');
INSERT INTO "jednostki" VALUES('NLE07','N','KULTURA LENDZIELSKA','GRUPA JORDANOWSKO-ŚLĄSKA','GRUPA JORDANOWSKO-ŚLĄSKA','GR. JORD.-ŚLĄS.','JO');
INSERT INTO "jednostki" VALUES('NLE08','N','KULTURA LENDZIELSKA','GRUPA LUBELSKO-WOŁYŃSKA','GRUPA LUBELSKO-WOŁYŃSKA','GR. LUBE.-WOŁY.','LU');
INSERT INTO "jednostki" VALUES('NLE09','N','KULTURA LENDZIELSKA','GRUPA MALICKA','GRUPA MALICKA','GR. MALICKA.','MA');
INSERT INTO "jednostki" VALUES('NLE10','N','KULTURA LENDZIELSKA','GRUPA MODLNICKA','GRUPA MODLNICKA','GR. MODLNICK.','MO');
INSERT INTO "jednostki" VALUES('NLE11','N','KULTURA LENDZIELSKA','GRUPA OCICKA','GRUPA OCICKA','GR. OCICKA.','OC');
INSERT INTO "jednostki" VALUES('NLE12','N','KULTURA LENDZIELSKA','GRUPA PLESZOWSKA','GRUPA PLESZOWSKA','GR. PLESZOWS.','PL');
INSERT INTO "jednostki" VALUES('NLE13','N','KULTURA LENDZIELSKA','GRUPA PLESZOWSKO-MODLNICKA','GRUPA PLESZOWSKO-MODLNICKA','GR. PLES.-MODL.','PL');
INSERT INTO "jednostki" VALUES('NLE14','N','KULTURA LENDZIELSKA','GRUPA SAMBORZECKO-OPATOWSKA','GRUPA SAMBORZECKO-OPATOWSKA','GR. SAMB.-OPAT.','SA');
INSERT INTO "jednostki" VALUES('NLE15','N','KULTURA LENDZIELSKA','GRUPA WYCIASKO-ZŁOTNICKA','GRUPA WYCIASKO-ZŁOTNICKA','GR. WYCI.-ZŁOT.','WY');
INSERT INTO "jednostki" VALUES('NLE16','N','KULTURA LENDZIELSKA','GRUPA ZARZYCKA','GRUPA ZARZYCKA','GR. ZARZYCKA.','ZA');
INSERT INTO "jednostki" VALUES('NLP','N','KULTURA LENDZIELSKO-POLGARSKA',NULL,'KULTURA LENDZIELSKO-POLGARSKA','KUL. LEND.-POLG.','LE');
INSERT INTO "jednostki" VALUES('NLP01','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA BRZESKO-KUJAWSKA','GRUPA BRZESKO-KUJAWSKA','GR. BRZE.-KUJA.','BR');
INSERT INTO "jednostki" VALUES('NLP02','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA CERAMIKI BIAŁO-MALOWANEJ','GRUPA CERAMIKI BIAŁO-MALOWANEJ','GR. CERA. BIAŁ.','CE');
INSERT INTO "jednostki" VALUES('NLP03','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA GÓROWSKA','GRUPA GÓROWSKA','GR. GÓROWSKA.','GÓ');
INSERT INTO "jednostki" VALUES('NLP04','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA JANÓWECKA','GRUPA JANÓWECKA','GR. JANÓWECK.','JA');
INSERT INTO "jednostki" VALUES('NLP05','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA JORDANOWSKA','GRUPA JORDANOWSKA','GR. JORDANOW.','JO');
INSERT INTO "jednostki" VALUES('NLP06','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA JORDANOWSKO-ŚLĄSKA','GRUPA JORDANOWSKO-ŚLĄSKA','GR. JORD.-ŚLĄS.','JO');
INSERT INTO "jednostki" VALUES('NLP07','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA LUBELSKO-WOŁYŃSKA','GRUPA LUBELSKO-WOŁYŃSKA','GR. LUBE.-WOŁY.','LU');
INSERT INTO "jednostki" VALUES('NLP08','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA MALICKA','GRUPA MALICKA','GR. MALICKA.','MA');
INSERT INTO "jednostki" VALUES('NLP09','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA MODLNICKA','GRUPA MODLNICKA','GR. MODLNICK.','MO');
INSERT INTO "jednostki" VALUES('NLP10','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA OCICKA','GRUPA OCICKA','GR. OCICKA.','OC');
INSERT INTO "jednostki" VALUES('NLP11','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA PLESZOWSKA','GRUPA PLESZOWSKA','GR. PLESZOWS.','PL');
INSERT INTO "jednostki" VALUES('NLP12','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA PLESZOWSKO-MODLNICKA','GRUPA PLESZOWSKO-MODLNICKA','GR. PLES.-MODL.','PL');
INSERT INTO "jednostki" VALUES('NLP13','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA SAMBORZECKO-OPATOWSKA','GRUPA SAMBORZECKO-OPATOWSKA','GR. SAMB.-OPAT.','SA');
INSERT INTO "jednostki" VALUES('NLP14','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA WYCIASKO-ZŁOTNICKA','GRUPA WYCIASKO-ZŁOTNICKA','GR. WYCI.-ZŁOT.','WY');
INSERT INTO "jednostki" VALUES('NLP15','N','KULTURA LENDZIELSKO-POLGARSKA','GRUPA ZARZYCKA','GRUPA ZARZYCKA','GR. ZARZYCKA.','ZA');
INSERT INTO "jednostki" VALUES('NLN','N','KULTURA LINIŃSKA',NULL,'KULTURA LINIŃSKA','KUL. LINIŃSKA.','LI');
INSERT INTO "jednostki" VALUES('NMA','N','KULTURA MALICKA',NULL,'KULTURA MALICKA','KUL. MALICKA.','MA');
INSERT INTO "jednostki" VALUES('NMZ','N','KULTURA MAZOWIECKA',NULL,'KULTURA MAZOWIECKA','KUL. MAZOWIEC.','MA');
INSERT INTO "jednostki" VALUES('NND','N','KULTURA NADCISAŃSKA',NULL,'KULTURA NADCISAŃSKA','KUL. NADCISAŃ.','NA');
INSERT INTO "jednostki" VALUES('NNR','N','KULTURA NARVSKA/NAREWSKA/NARVA',NULL,'KULTURA NARVSKA/NAREWSKA/NARVA','KUL. NARVSKA/.','NA');
INSERT INTO "jednostki" VALUES('NSL','N','NEOLIT STREFY LEŚNEJ',NULL,'NEOLIT STREFY LEŚNEJ','NEOLIT STREFY LEŚNEJ','ST');
INSERT INTO "jednostki" VALUES('NNI','N','KULTURA NIEMIEŃSKA',NULL,'KULTURA NIEMIEŃSKA','KUL. NIEMIEŃS.','NI');
INSERT INTO "jednostki" VALUES('NOL','N','KULTURA OŁONIECKA',NULL,'KULTURA OŁONIECKA','KUL. OŁONIECK.','OŁ');
INSERT INTO "jednostki" VALUES('NPA','N','PARANEOLIT',NULL,'PARANEOLIT','PARANEOLIT','PA');
INSERT INTO "jednostki" VALUES('NPL','N','KULTURA POLGARSKA',NULL,'KULTURA POLGARSKA','KUL. POLGARSK.','PO');
INSERT INTO "jednostki" VALUES('NGC','N','POLSKA GRUPA CERAMIKI GRZEBYKOWEJ',NULL,'POLSKA GRUPA CERAMIKI GRZEBYKOWEJ','POLSKA GRUPA CERAMIKI GRZEBYKOWEJ','GR');
INSERT INTO "jednostki" VALUES('NPO','N','KULTURA POSTJANISŁAWICKA',NULL,'KULTURA POSTJANISŁAWICKA','KUL. POST. .','PO');
INSERT INTO "jednostki" VALUES('NPE','N','KULTURA PÓŁNOCNO-EURAZJATYCKA',NULL,'KULTURA PÓŁNOCNO-EURAZJATYCKA','KUL. PÓŁN.-EURA.','PÓ');
INSERT INTO "jednostki" VALUES('NPC','N','KULTURA PÓŹNEJ CERAMIKI WSTĘGOWEJ',NULL,'KULTURA PÓŹNEJ CERAMIKI WSTĘGOWEJ','KUL. PÓŹN. CERA.','PÓ');
INSERT INTO "jednostki" VALUES('NPR','N','KULTURA PRAFIŃSKA',NULL,'KULTURA PRAFIŃSKA','KUL. PRAFIŃSK.','PR');
INSERT INTO "jednostki" VALUES('NPR01','N','KULTURA PRAFIŃSKA','GRUPA PÓŁNOCNO-WSCHODNIA','GRUPA PÓŁNOCNO-WSCHODNIA','GR. PÓŁN.-WSCH.','PÓ');
INSERT INTO "jednostki" VALUES('NPR02','N','KULTURA PRAFIŃSKA','GRUPA POŁUDNIOWA (MAZOWIECKA)','GRUPA POŁUDNIOWA (MAZOWIECKA)','GR. POŁU. (MAZ.','PO');
INSERT INTO "jednostki" VALUES('NUG','N','KULTURA PRAUGROFIŃSKA',NULL,'KULTURA PRAUGROFIŃSKA','KUL. PRAUGROF.','PR');
INSERT INTO "jednostki" VALUES('NPM','N','KULTURA PRZYMORSKA',NULL,'KULTURA PRZYMORSKA','KUL. PRZYMORS.','PR');
INSERT INTO "jednostki" VALUES('NPD','N','KULTURA PUCHARÓW DZWONOWATYCH',NULL,'KULTURA PUCHARÓW DZWONOWATYCH','KUL. PUCH. DZWO.','PU');
INSERT INTO "jednostki" VALUES('NLJ','N','KULTURA PUCHARÓW LEJKOWATYCH',NULL,'KULTURA PUCHARÓW LEJKOWATYCH','KUL. PUCH. LEJK.','PU');
INSERT INTO "jednostki" VALUES('NLJ01','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA CHEŁMIŃSKA','GRUPA CHEŁMIŃSKA','GR. CHEŁMIŃS.','CH');
INSERT INTO "jednostki" VALUES('NLJ02','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA MĄTEWSKA','GRUPA MĄTEWSKA','GR. MĄTEWSKA.','MĄ');
INSERT INTO "jednostki" VALUES('NLJ03','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA MROWIŃSKA','GRUPA MROWIŃSKA','GR. MROWIŃSK.','MR');
INSERT INTO "jednostki" VALUES('NLJ04','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA POŁUDNIOWA','GRUPA POŁUDNIOWA','GR. POŁUDNIO.','PO');
INSERT INTO "jednostki" VALUES('NLJ05','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA POŁUDNIOWO-WSCHODNIA','GRUPA POŁUDNIOWO-WSCHODNIA','GR. POŁU.-WSCH.','PO');
INSERT INTO "jednostki" VALUES('NLJ06','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA RADZIEJOWSKA','GRUPA RADZIEJOWSKA','GR. RADZIEJO.','RA');
INSERT INTO "jednostki" VALUES('NLJ07','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA ŚLĄSKO-MORAWSKA','GRUPA ŚLĄSKO-MORAWSKA','GR. ŚLĄS.-MORA.','ŚL');
INSERT INTO "jednostki" VALUES('NLJ08','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA USTOWSKA','GRUPA USTOWSKA','GR. USTOWSKA.','US');
INSERT INTO "jednostki" VALUES('NLJ09','N','KULTURA PUCHARÓW LEJKOWATYCH','GRUPA WSCHODNIA','GRUPA WSCHODNIA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('NRO','N','KULTURA RÖSSEŃSKA',NULL,'KULTURA RÖSSEŃSKA','KUL. RÖSSEŃSK.','RÖ');
INSERT INTO "jednostki" VALUES('NRZ','N','KULTURA RZUCEWSKA',NULL,'KULTURA RZUCEWSKA','KUL. RZUCEWSK.','RZ');
INSERT INTO "jednostki" VALUES('NSN','N','SUBNEOLIT',NULL,'SUBNEOLIT','SUBNEOLIT','SU');
INSERT INTO "jednostki" VALUES('NSD','N','KULTURA ŚRODKOWODNIEPRZAŃSKA',NULL,'KULTURA ŚRODKOWODNIEPRZAŃSKA','KUL. ŚRODKOWO.','ŚR');
INSERT INTO "jednostki" VALUES('NTB','N','KULTURA TOPORÓW BOJOWYCH',NULL,'KULTURA TOPORÓW BOJOWYCH','KUL. TOPO. BOJO.','TO');
INSERT INTO "jednostki" VALUES('NTR','N','KULTURA TRYPOLSKA',NULL,'KULTURA TRYPOLSKA','KUL. TRYPOLSK.','TR');
INSERT INTO "jednostki" VALUES('NWA','N','KULTURA WALTENIENBURSKA',NULL,'KULTURA WALTENIENBURSKA','KUL. WALTENIE.','WA');
INSERT INTO "jednostki" VALUES('NWB','N','KULTURA WALTENIENBURSKO-BERNBURSKA',NULL,'KULTURA WALTENIENBURSKO-BERNBURSKA','KUL. WALT.-BERN.','WA');
INSERT INTO "jednostki" VALUES('NWN','N','KULTURA WIŚLAŃSKO-NIEMIEŃSKA',NULL,'KULTURA WIŚLAŃSKO-NIEMIEŃSKA','KUL. WIŚL.-NIEM.','WI');
INSERT INTO "jednostki" VALUES('NWS','N','KULTURA WSCHODNIOBAŁTYCKA',NULL,'KULTURA WSCHODNIOBAŁTYCKA','KUL. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('NZE','N','KULTURA ZEDMARSKA/ZEDMAR',NULL,'KULTURA ZEDMARSKA/ZEDMAR','KUL. ZEDMARSK.','ZE');
INSERT INTO "jednostki" VALUES('NZL','N','KULTURA ZŁOCKA',NULL,'KULTURA ZŁOCKA','KUL. ZŁOCKA.','ZŁ');
INSERT INTO "jednostki" VALUES('NLI','N','GRUPA LINIŃSKA',NULL,'GRUPA LINIŃSKA','GR. LINI. .','LI');
INSERT INTO "jednostki" VALUES('NPU','N','GRUPA POLSKO-UKRAIŃSKA',NULL,'GRUPA POLSKO-UKRAIŃSKA','GR. POLS.-UKRA.','PO');
INSERT INTO "jednostki" VALUES('NSO','N','GRUPA SOKOŁÓWECKA',NULL,'GRUPA SOKOŁÓWECKA','GR. SOKOŁÓWE.','SO');
INSERT INTO "jednostki" VALUES('B','B',NULL,NULL,'B','B','BR');
INSERT INTO "jednostki" VALUES('BIW','B','KULTURA IWIEŃSKA',NULL,'KULTURA IWIEŃSKA','KUL. IWIEŃSKA.','IW');
INSERT INTO "jednostki" VALUES('BLZ','B','KULTURA ŁUŻYCKA',NULL,'KULTURA ŁUŻYCKA','KUL. ŁUŻYCKA.','ŁU');
INSERT INTO "jednostki" VALUES('BLZ01','B','KULTURA ŁUŻYCKA','GRUPA BRANDENBURSKO-LUBUSKA','GRUPA BRANDENBURSKO-LUBUSKA','GR. BRAN.-LUBU.','BR');
INSERT INTO "jednostki" VALUES('BLZ02','B','KULTURA ŁUŻYCKA','GRUPA CHEŁMIŃSKA','GRUPA CHEŁMIŃSKA','GR. CHEŁMIŃS.','CH');
INSERT INTO "jednostki" VALUES('BLZ03','B','KULTURA ŁUŻYCKA','GRUPA GÓRNOŚLĄSKO-MAŁOPOLSKA','GRUPA GÓRNOŚLĄSKO-MAŁOPOLSKA','GR. GÓRN.-MAŁO.','GÓ');
INSERT INTO "jednostki" VALUES('BLZ04','B','KULTURA ŁUŻYCKA','GRUPA KONSTANTYNOWSKA/ŚRODKOWOPOLSKA','GRUPA KONSTANTYNOWSKA/ŚRODKOWOPOLSKA','GR. KONSTANT.','KO');
INSERT INTO "jednostki" VALUES('BLZ05','B','KULTURA ŁUŻYCKA','GRUPA MAZOWIECKO-PODLASKA/WSCHODNIOMAZOWIECKO-PODLASKA','GRUPA MAZOWIECKO-PODLASKA/WSCHODNIOMAZOWIECKO-PODLASKA','GR. MAZO.-PODL.','MA');
INSERT INTO "jednostki" VALUES('BLZ06','B','KULTURA ŁUŻYCKA','GRUPA PÓŁNOCNOMAZOWIECKA','GRUPA PÓŁNOCNOMAZOWIECKA','GR. PÓŁNOCNO.','PÓ');
INSERT INTO "jednostki" VALUES('BLZ07','B','KULTURA ŁUŻYCKA','GRUPA SASKO-ŁUŻYCKA','GRUPA SASKO-ŁUŻYCKA','GR. SASK.-ŁUŻY.','SA');
INSERT INTO "jednostki" VALUES('BLZ08','B','KULTURA ŁUŻYCKA','GRUPA ŚLĄSKA','GRUPA ŚLĄSKA','GR. ŚLĄSKA.','ŚL');
INSERT INTO "jednostki" VALUES('BLZ09','B','KULTURA ŁUŻYCKA','GRUPA TARNOBRZESKA','GRUPA TARNOBRZESKA','GR. TARNOBRZ.','TA');
INSERT INTO "jednostki" VALUES('BLZ10','B','KULTURA ŁUŻYCKA','GRUPA ULWÓWECKA (LUBELSKA)','GRUPA ULWÓWECKA (LUBELSKA)','GR. ULWÓ. (LUB.','UL');
INSERT INTO "jednostki" VALUES('BLZ11','B','KULTURA ŁUŻYCKA','GRUPA WARMIŃSKO-MAZURSKA','GRUPA WARMIŃSKO-MAZURSKA','GR. WARM.-MAZU.','WA');
INSERT INTO "jednostki" VALUES('BLZ12','B','KULTURA ŁUŻYCKA','GRUPA WSCHODNIOPOMORSKA (KASZUBSKA)','GRUPA WSCHODNIOPOMORSKA (KASZUBSKA)','GR. WSCH. (KAS.','WS');
INSERT INTO "jednostki" VALUES('BLZ13','B','KULTURA ŁUŻYCKA','GRUPA WSCHODNIOWIELKOPOLSKA','GRUPA WSCHODNIOWIELKOPOLSKA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('BLZ14','B','KULTURA ŁUŻYCKA','GRUPA ZACHODNIOPOMORSKA','GRUPA ZACHODNIOPOMORSKA','GR. ZACHODNI.','ZA');
INSERT INTO "jednostki" VALUES('BMI','B','KULTURA MIERZANOWICKA',NULL,'KULTURA MIERZANOWICKA','KUL. MIERZANO.','MI');
INSERT INTO "jednostki" VALUES('BMI01','B','KULTURA MIERZANOWICKA','GRUPA GIEBUŁTOWSKA','GRUPA GIEBUŁTOWSKA','GR. GIEBUŁTO.','GI');
INSERT INTO "jednostki" VALUES('BMI02','B','KULTURA MIERZANOWICKA','GRUPA IWANOWICKA','GRUPA IWANOWICKA','GR. IWANOWIC.','IW');
INSERT INTO "jednostki" VALUES('BMI03','B','KULTURA MIERZANOWICKA','GRUPA PLESZOWSKA','GRUPA PLESZOWSKA','GR. PLESZOWS.','PL');
INSERT INTO "jednostki" VALUES('BMI04','B','KULTURA MIERZANOWICKA','GRUPA SAMBORZECKA','GRUPA SAMBORZECKA','GR. SAMBORZE.','SA');
INSERT INTO "jednostki" VALUES('BMI05','B','KULTURA MIERZANOWICKA','GRUPA SZARBIAŃSKA','GRUPA SZARBIAŃSKA','GR. SZARBIAŃ.','SZ');
INSERT INTO "jednostki" VALUES('BMO','B','KULTURA MOGIŁOWA (PRZEDŁUŻYCKA)',NULL,'KULTURA MOGIŁOWA (PRZEDŁUŻYCKA)','KUL. MOGI. (PRZ.','MO');
INSERT INTO "jednostki" VALUES('BMO01','B','KULTURA MOGIŁOWA (PRZEDŁUŻYCKA)','GRUPA POŁUDNIOWOŚLĄSKA','GRUPA POŁUDNIOWOŚLĄSKA','GR. POŁUDNIO.','PO');
INSERT INTO "jednostki" VALUES('BMO02','B','KULTURA MOGIŁOWA (PRZEDŁUŻYCKA)','GRUPA PÓŁNOCNOŚLĄSKO-WIELKOPOLSKA','GRUPA PÓŁNOCNOŚLĄSKO-WIELKOPOLSKA','GR. PÓŁN.-WIEL.','PÓ');
INSERT INTO "jednostki" VALUES('BMO03','B','KULTURA MOGIŁOWA (PRZEDŁUŻYCKA)','GRUPA WSCHODNIOWIELKOPOLSKO-KUJAWSKA','GRUPA WSCHODNIOWIELKOPOLSKO-KUJAWSKA','GR. WSCH.-KUJA.','WS');
INSERT INTO "jednostki" VALUES('BOT','B','KULTURA OTOMANI',NULL,'KULTURA OTOMANI','KUL. OTOMANI.','OT');
INSERT INTO "jednostki" VALUES('BST','B','KULTURA STRZYŻOWSKA',NULL,'KULTURA STRZYŻOWSKA','KUL. STRZYŻOW.','ST');
INSERT INTO "jednostki" VALUES('BTR','B','KULTURA TRZCINIECKA',NULL,'KULTURA TRZCINIECKA','KUL. TRZCINIE.','TR');
INSERT INTO "jednostki" VALUES('BTR01','B','KULTURA TRZCINIECKA','GRUPA LUBELSKA','GRUPA LUBELSKA','GR. LUBELSKA.','LU');
INSERT INTO "jednostki" VALUES('BTR02','B','KULTURA TRZCINIECKA','GRUPA ŁUBIEŃSKA','GRUPA ŁUBIEŃSKA','GR. ŁUBIEŃSK.','ŁU');
INSERT INTO "jednostki" VALUES('BTR03','B','KULTURA TRZCINIECKA','GRUPA MAZOWIECKO-PODLASKA','GRUPA MAZOWIECKO-PODLASKA','GR. MAZO.-PODL.','MA');
INSERT INTO "jednostki" VALUES('BTR04','B','KULTURA TRZCINIECKA','GRUPA OPATOWSKA','GRUPA OPATOWSKA','GR. OPATOWSK.','OP');
INSERT INTO "jednostki" VALUES('BUN','B','KULTURA UNIETYCKA',NULL,'KULTURA UNIETYCKA','KUL. UNIETYCK.','UN');
INSERT INTO "jednostki" VALUES('BUN01','B','KULTURA UNIETYCKA','GRUPA ŁUŻYCKA','GRUPA ŁUŻYCKA','GR. ŁUŻYCKA.','ŁU');
INSERT INTO "jednostki" VALUES('BUN02','B','KULTURA UNIETYCKA','GRUPA ŚLĄSKO-WIELKOPOLSKA','GRUPA ŚLĄSKO-WIELKOPOLSKA','GR. ŚLĄS.-WIEL.','ŚL');
INSERT INTO "jednostki" VALUES('BNC','B','GRUPA NOWOCERKWIAŃSKA',NULL,'GRUPA NOWOCERKWIAŃSKA','GR. NOWOCERK.','NO');
INSERT INTO "jednostki" VALUES('BOS','B','GRUPA OSTROWICKA',NULL,'GRUPA OSTROWICKA','GR. OSTROWIC.','OS');
INSERT INTO "jednostki" VALUES('BPL','B','GRUPA PŁONIE',NULL,'GRUPA PŁONIE','GR. PŁONIE.','PŁ');
INSERT INTO "jednostki" VALUES('BPL01','B','GRUPA PŁONIE','GRUPA GASI','GRUPA GASI','GR. GASI.','GA');
INSERT INTO "jednostki" VALUES('Z','Z',NULL,NULL,'Z','Z','ŻE');
INSERT INTO "jednostki" VALUES('ZBO','Z','KULTURA BOGACZEWSKA',NULL,'KULTURA BOGACZEWSKA','KUL. BOGACZEW.','BO');
INSERT INTO "jednostki" VALUES('ZCS','Z','KULTURA CERAMIKI SZTRYCHOWANEJ',NULL,'KULTURA CERAMIKI SZTRYCHOWANEJ','KUL. CERA. SZTR.','CE');
INSERT INTO "jednostki" VALUES('ZDK','Z','KULTURA DOLLKEIM-KOVROVO',NULL,'KULTURA DOLLKEIM-KOVROVO','KUL. DOLL.-KOVR.','DO');
INSERT INTO "jednostki" VALUES('ZGK','Z','KULTURA GROBÓW KLOSZOWYCH',NULL,'KULTURA GROBÓW KLOSZOWYCH','KUL. GROB. KLOS.','GR');
INSERT INTO "jednostki" VALUES('ZJA','Z','KULTURA JASTORFSKA',NULL,'KULTURA JASTORFSKA','KUL. JASTORFS.','JA');
INSERT INTO "jednostki" VALUES('ZJA01','Z','KULTURA JASTORFSKA','GRUPA CZERNICZYŃSKA (DAWNIEJ): MATERIAŁY TYPU WERBKOWICE, OSADY TYPU BRZEŚĆ KUJAWSKI, OSADY TYPU IZDEBNO','GRUPA CZERNICZYŃSKA (DAWNIEJ): MATERIAŁY TYPU WERBKOWICE, OSADY TYPU BRZEŚĆ KUJAWSKI, OSADY TYPU IZDEBNO','GR. CZER. (DAW.','CZ');
INSERT INTO "jednostki" VALUES('ZJA02','Z','KULTURA JASTORFSKA','GRUPA GUBIŃSKA','GRUPA GUBIŃSKA','GR. GUBIŃSKA.','GU');
INSERT INTO "jednostki" VALUES('ZJA03','Z','KULTURA JASTORFSKA','GRUPA NADODRZAŃSKA','GRUPA NADODRZAŃSKA','GR. NADODRZA.','NA');
INSERT INTO "jednostki" VALUES('ZKU','Z','KULTURA KURHANÓW ZACHODNIOBAŁTYJSKICH',NULL,'KULTURA KURHANÓW ZACHODNIOBAŁTYJSKICH','KUL. KURH. ZACH.','KU');
INSERT INTO "jednostki" VALUES('ZLA','Z','KULTURA LATEŃSKA',NULL,'KULTURA LATEŃSKA','KUL. LATEŃSKA.','LA');
INSERT INTO "jednostki" VALUES('ZLU','Z','KULTURA LUBOSZYCKA',NULL,'KULTURA LUBOSZYCKA','KUL. LUBOSZYC.','LU');
INSERT INTO "jednostki" VALUES('ZLZ','Z','KULTURA ŁUŻYCKA',NULL,'KULTURA ŁUŻYCKA','KUL. ŁUŻYCKA.','ŁU');
INSERT INTO "jednostki" VALUES('ZLZ01','Z','KULTURA ŁUŻYCKA','GRUPA BIAŁOWICKA/SASKO-ŁUŻYCKA','GRUPA BIAŁOWICKA/SASKO-ŁUŻYCKA','GR. BIAŁ.-ŁUŻY.','BI');
INSERT INTO "jednostki" VALUES('ZLZ02','Z','KULTURA ŁUŻYCKA','GRUPA CHEŁMIŃSKA','GRUPA CHEŁMIŃSKA','GR. CHEŁMIŃS.','CH');
INSERT INTO "jednostki" VALUES('ZLZ03','Z','KULTURA ŁUŻYCKA','GRUPA GÓRNOŚLĄSKO-MAŁOPOLSKA','GRUPA GÓRNOŚLĄSKO-MAŁOPOLSKA','GR. GÓRN.-MAŁO.','GÓ');
INSERT INTO "jednostki" VALUES('ZLZ04','Z','KULTURA ŁUŻYCKA','GRUPA GÓRZYCKA','GRUPA GÓRZYCKA','GR. GÓRZYCKA.','GÓ');
INSERT INTO "jednostki" VALUES('ZLZ05','Z','KULTURA ŁUŻYCKA','GRUPA KASZUBSKA','GRUPA KASZUBSKA','GR. KASZUBSK.','KA');
INSERT INTO "jednostki" VALUES('ZLZ06','Z','KULTURA ŁUŻYCKA','GRUPA MAZOWIECKO-PODLASKA','GRUPA MAZOWIECKO-PODLASKA','GR. MAZO.-PODL.','MA');
INSERT INTO "jednostki" VALUES('ZLZ07','Z','KULTURA ŁUŻYCKA','GRUPA ŚLĄSKA','GRUPA ŚLĄSKA','GR. ŚLĄSKA.','ŚL');
INSERT INTO "jednostki" VALUES('ZLZ08','Z','KULTURA ŁUŻYCKA','GRUPA TARNOBRZESKA','GRUPA TARNOBRZESKA','GR. TARNOBRZ.','TA');
INSERT INTO "jednostki" VALUES('ZLZ09','Z','KULTURA ŁUŻYCKA','GRUPA WARMIŃSKO-MAZURSKA','GRUPA WARMIŃSKO-MAZURSKA','GR. WARM.-MAZU.','WA');
INSERT INTO "jednostki" VALUES('ZLZ10','Z','KULTURA ŁUŻYCKA','GRUPA WSCHODNIA','GRUPA WSCHODNIA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('ZLZ11','Z','KULTURA ŁUŻYCKA','GRUPA WSCHODNIOWIELKOPOLSKA','GRUPA WSCHODNIOWIELKOPOLSKA','GR. WSCHODNI.','WS');
INSERT INTO "jednostki" VALUES('ZMI','Z','KULTURA MIŁOGRADZKA',NULL,'KULTURA MIŁOGRADZKA','KUL. MIŁOGRAD.','MI');
INSERT INTO "jednostki" VALUES('ZOK','Z','KULTURA OKSYWSKA',NULL,'KULTURA OKSYWSKA','KUL. OKSYWSKA.','OK');
INSERT INTO "jednostki" VALUES('ZPO','Z','KULTURA POMORSKA',NULL,'KULTURA POMORSKA','KUL. POMORSKA.','PO');
INSERT INTO "jednostki" VALUES('ZPR','Z','KULTURA PRZEWORSKA',NULL,'KULTURA PRZEWORSKA','KUL. PRZEWORS.','PR');
INSERT INTO "jednostki" VALUES('ZPU','Z','KULTURA PUCHOWSKA',NULL,'KULTURA PUCHOWSKA','KUL. PUCHOWSK.','PU');
INSERT INTO "jednostki" VALUES('ZSU','Z','KULTURA SUDOWSKA',NULL,'KULTURA SUDOWSKA','KUL. SUDOWSKA.','SU');
INSERT INTO "jednostki" VALUES('ZDA','Z','UGRUPOWANIA DACKIE',NULL,'UGRUPOWANIA DACKIE','UGRUPOWANIA DACKIE','DA');
INSERT INTO "jednostki" VALUES('ZDA01','Z','UGRUPOWANIA DACKIE','MATERIAŁY TYPU WIETRZNO-SOLINA','MATERIAŁY TYPU WIETRZNO-SOLINA','MATERIAŁY TYPU WIETRZNO-SOLINA','TY');
INSERT INTO "jednostki" VALUES('ZDA02','Z','UGRUPOWANIA DACKIE','GRUPA PÓŁNOCNOKARPACKA','GRUPA PÓŁNOCNOKARPACKA','GR. PÓŁNOCNO.','PÓ');
INSERT INTO "jednostki" VALUES('ZWZ','Z','KULTURA WCZESNEJ EPOKI ŻELAZA NA POMORZU ZACHODNIM',NULL,'KULTURA WCZESNEJ EPOKI ŻELAZA NA POMORZU ZACHODNIM','KUL. WCZE. EPOK.','WC');
INSERT INTO "jednostki" VALUES('ZWI','Z','KULTURA WIELBARSKA',NULL,'KULTURA WIELBARSKA','KUL. WIELBARS.','WI');
INSERT INTO "jednostki" VALUES('ZZA','Z','KULTURA ZARUBINIECKA',NULL,'KULTURA ZARUBINIECKA','KUL. ZARUBINI.','ZA');
INSERT INTO "jednostki" VALUES('ZDE','Z','GRUPA DĘBCZYŃSKA',NULL,'GRUPA DĘBCZYŃSKA','GR. DĘBCZYŃS.','DĘ');
INSERT INTO "jednostki" VALUES('ZEL','Z','GRUPA ELBLĄSKA',NULL,'GRUPA ELBLĄSKA','GR. ELBLĄSKA.','EL');
INSERT INTO "jednostki" VALUES('ZGU','Z','GRUPA GUSTOWSKA',NULL,'GRUPA GUSTOWSKA','GR. GUSTOWSK.','GU');
INSERT INTO "jednostki" VALUES('ZLB','Z','GRUPA LUBUSKA',NULL,'GRUPA LUBUSKA','GR. LUBUSKA.','LU');
INSERT INTO "jednostki" VALUES('ZMA','Z','GRUPA MASŁOMĘCKA',NULL,'GRUPA MASŁOMĘCKA','GR. MASŁOMĘC.','MA');
INSERT INTO "jednostki" VALUES('ZOL','Z','GRUPA OLSZTYŃSKA',NULL,'GRUPA OLSZTYŃSKA','GR. OLSZTYŃS.','OL');
INSERT INTO "jednostki" VALUES('ZTY','Z','GRUPA TYNIECKA',NULL,'GRUPA TYNIECKA','GR. TYNIECKA.','TY');
INSERT INTO "jednostki" VALUES('W','WIELOKULTUROWE',NULL,NULL,'WIELOKULTUROWE','WIELOKULTUROWE','WI');
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE trasy(
  id integer NOT NULL,
  rodzaj_badan varchar(2) not null default '?', -- L - lot, P - powierzchniowe, W - weryfikacje, ? - nieokreslone
  data varchar(10) not null,
  autor varchar(100) not null,
  rozpoczecie varchar(25),
  zakonczenie varchar(25),
  czestotliwosc integer default 0, -- czestotliwosc odczytow w sekundach
  uwagi varchar(255),
  wspolrzedne LINESTRING,
  CONSTRAINT pk_trasy PRIMARY KEY (id)
);
CREATE TRIGGER "ggi_trasy_wspolrzedne" BEFORE INSERT ON trasy
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'trasy.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'trasy' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
CREATE TRIGGER "ggu_trasy_wspolrzedne" BEFORE UPDATE ON trasy
FOR EACH ROW BEGIN
SELECT RAISE(ROLLBACK, 'trasy.wspolrzedne violates Geometry constraint [geom-type or SRID not allowed]')
WHERE (SELECT type FROM geometry_columns
WHERE f_table_name = 'trasy' AND f_geometry_column = 'wspolrzedne'
AND GeometryConstraints(NEW.wspolrzedne, type, srid, 'XY') = 1) IS NULL;
END;
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE ustawienia(klucz varchar(10) primary key, wartosc varchar(20));
COMMIT;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE geometry_columns (
f_table_name TEXT NOT NULL,
f_geometry_column TEXT NOT NULL,
type TEXT NOT NULL,
coord_dimension TEXT NOT NULL,
srid INTEGER NOT NULL,
spatial_index_enabled INTEGER NOT NULL,
CONSTRAINT pk_geom_cols PRIMARY KEY (f_table_name, f_geometry_column),
CONSTRAINT fk_gc_srs FOREIGN KEY (srid) REFERENCES spatial_ref_sys (srid));
INSERT INTO "geometry_columns" VALUES('trasy','wspolrzedne','LINESTRING','XY',2180,0);
INSERT INTO "geometry_columns" VALUES('miejsca','wspolrzedne','POINT','XY',2180,0);
INSERT INTO "geometry_columns" VALUES('stanowiska','wspolrzedne','POLYGON','XY',2180,0);
CREATE INDEX idx_srid_geocols ON geometry_columns
(srid);
COMMIT;
